ls

In [2]:
import pandas as pd 
nandf=pd.read_table("p015036_sepsis_sofa_qsofa_with_nan.psv",sep="|")

In [6]:
nandf

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
0,NaN,NaN,NaN,NaN,NaN,1,0,0,0
1,20.00,NaN,NaN,NaN,NaN,2,0,0,0
2,19.00,NaN,NaN,NaN,NaN,3,0,0,0
3,24.00,NaN,NaN,2.3,3.4,4,0,1,1
4,25.00,NaN,NaN,NaN,NaN,5,0,1,0
5,26.00,NaN,NaN,NaN,NaN,6,0,1,0
6,28.50,NaN,187.0,2.7,3.7,7,0,1,1
7,24.25,NaN,NaN,NaN,NaN,8,0,1,0
8,15.00,NaN,NaN,NaN,NaN,9,0,0,0
9,25.00,NaN,NaN,NaN,NaN,10,0,1,0
10,26.00,NaN,NaN,NaN,NaN,11,0,1,0
11,NaN,NaN,158.0,3.0,3.8,12,0,0,0
12,25.50,NaN,NaN,NaN,NaN,13,0,1,0
13,19.00,NaN,NaN,NaN,NaN,14,0,0,0
14,20.00,NaN,NaN,NaN,NaN,15,0,0,0
15,20.50,NaN,NaN,NaN,NaN,16,0,0,0
16,20.50,NaN,NaN,NaN,NaN,17,0,0,0
17,21.50,NaN,159.0,NaN,4.3,18,0,0,0
18,21.00,NaN,NaN,NaN,NaN,19,0,0,0
19,18.00,NaN,NaN,NaN,NaN,20,0,0,0
20,18.75,NaN,150.0,3.9,4.5,21,0,0,0
21,24.00,NaN,NaN,NaN,NaN,22,0,1,0
22,29.00,101.0,NaN,NaN,NaN,23,0,1,0
23,28.00,106.0,NaN,NaN,NaN,24,0,1,0
24,32.00,115.5,NaN,NaN,NaN,25,0,1,0
25,23.00,106.0,119.0,3.2,4.4,26,0,1,1
26,30.00,118.0,NaN,NaN,NaN,27,0,1,0
27,25.00,121.0,NaN,NaN,NaN,28,0,1,0
28,25.00,121.5,NaN,NaN,NaN,29,0,1,0
29,26.00,121.0,NaN,NaN,NaN,30,0,1,0
30,25.00,118.0,NaN,NaN,NaN,31,0,1,0
31,30.00,121.0,126.0,4.3,4.6,32,0,1,1
32,25.00,117.0,NaN,NaN,NaN,33,0,1,0
33,22.75,110.0,NaN,NaN,NaN,34,0,1,0
34,23.00,107.0,NaN,NaN,NaN,35,0,1,0
35,24.00,110.5,124.0,4.9,4.7,36,0,1,1
36,24.00,97.0,NaN,NaN,4.3,37,0,1,1
37,21.00,101.0,NaN,NaN,NaN,38,0,0,0
38,24.00,107.5,NaN,NaN,NaN,39,0,1,0
39,24.00,81.5,106.0,5.2,3.6,40,1,1,1
40,20.00,90.0,NaN,NaN,NaN,41,1,1,0
41,20.00,96.0,NaN,NaN,NaN,42,1,1,0
42,20.00,93.0,NaN,NaN,NaN,43,1,1,0
43,20.00,97.5,NaN,NaN,NaN,44,1,1,0
44,20.00,110.0,133.0,5.7,3.0,45,1,0,0
45,20.00,100.5,NaN,NaN,NaN,46,1,0,0
46,20.00,104.5,NaN,NaN,NaN,47,1,0,0
47,20.00,129.0,NaN,NaN,NaN,48,1,0,0
48,20.00,105.5,125.0,NaN,2.6,49,1,0,0

In [7]:
linear_interpolation=pd.read_table("p015036_sepsis_na_interpolation_linear.psv",sep="|")
spline_interpolation=pd.read_table("p015036_sepsis_na_interpolation_spline.psv",sep="|")
stine_interpolation=pd.read_table("p015036_sepsis_na_interpolation_stine.psv",sep="|")

In [12]:

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(linear_interpolation["Resp"], linear_interpolation["SBP"], linear_interpolation["Platelets"], linear_interpolation["Bilirubin_total"], linear_interpolation["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
linear_interpolation['qSOFA']=result_qsofa
linear_interpolation['SOFA']=result_sofa

linear_interpolation

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.00,101.0,187.000000,2.300000,3.400000,1,0,0,0
2,20.00,101.0,187.000000,2.300000,3.400000,2,0,0,0
3,19.00,101.0,187.000000,2.300000,3.400000,3,0,0,0
4,24.00,101.0,187.000000,2.300000,3.400000,4,0,1,1
5,25.00,101.0,187.000000,2.433333,3.500000,5,0,1,1
6,26.00,101.0,187.000000,2.566667,3.600000,6,0,1,1
7,28.50,101.0,187.000000,2.700000,3.700000,7,0,1,1
8,24.25,101.0,181.200000,2.760000,3.720000,8,0,1,1
9,15.00,101.0,175.400000,2.820000,3.740000,9,0,0,0
10,25.00,101.0,169.600000,2.880000,3.760000,10,0,1,1
11,26.00,101.0,163.800000,2.940000,3.780000,11,0,1,1
12,25.75,101.0,158.000000,3.000000,3.800000,12,0,1,1
13,25.50,101.0,158.166667,3.100000,3.883333,13,0,1,1
14,19.00,101.0,158.333333,3.200000,3.966667,14,0,0,0
15,20.00,101.0,158.500000,3.300000,4.050000,15,0,0,0
16,20.50,101.0,158.666667,3.400000,4.133333,16,0,0,0
17,20.50,101.0,158.833333,3.500000,4.216667,17,0,0,0
18,21.50,101.0,159.000000,3.600000,4.300000,18,0,0,0
19,21.00,101.0,156.000000,3.700000,4.366667,19,0,0,0
20,18.00,101.0,153.000000,3.800000,4.433333,20,0,0,0
21,18.75,101.0,150.000000,3.900000,4.500000,21,0,0,0
22,24.00,101.0,143.800000,3.760000,4.480000,22,0,1,1
23,29.00,101.0,137.600000,3.620000,4.460000,23,0,1,1
24,28.00,106.0,131.400000,3.480000,4.440000,24,0,1,1
25,32.00,115.5,125.200000,3.340000,4.420000,25,0,1,1
26,23.00,106.0,119.000000,3.200000,4.400000,26,0,1,1
27,30.00,118.0,120.166667,3.383333,4.433333,27,0,1,1
28,25.00,121.0,121.333333,3.566667,4.466667,28,0,1,1
29,25.00,121.5,122.500000,3.750000,4.500000,29,0,1,1
30,26.00,121.0,123.666667,3.933333,4.533333,30,0,1,1
31,25.00,118.0,124.833333,4.116667,4.566667,31,0,1,1
32,30.00,121.0,126.000000,4.300000,4.600000,32,0,1,1
33,25.00,117.0,125.500000,4.450000,4.625000,33,0,1,1
34,22.75,110.0,125.000000,4.600000,4.650000,34,0,1,1
35,23.00,107.0,124.500000,4.750000,4.675000,35,0,1,1
36,24.00,110.5,124.000000,4.900000,4.700000,36,0,1,1
37,24.00,97.0,119.500000,4.975000,4.300000,37,0,1,1
38,21.00,101.0,115.000000,5.050000,4.066667,38,0,0,0
39,24.00,107.5,110.500000,5.125000,3.833333,39,0,1,1
40,24.00,81.5,106.000000,5.200000,3.600000,40,1,1,1
41,20.00,90.0,111.400000,5.300000,3.480000,41,1,1,1
42,20.00,96.0,116.800000,5.400000,3.360000,42,1,1,1
43,20.00,93.0,122.200000,5.500000,3.240000,43,1,1,1
44,20.00,97.5,127.600000,5.600000,3.120000,44,1,1,1
45,20.00,110.0,133.000000,5.700000,3.000000,45,1,0,0
46,20.00,100.5,131.000000,5.700000,2.900000,46,1,0,0
47,20.00,104.5,129.000000,5.700000,2.800000,47,1,0,0
48,20.00,129.0,127.000000,5.700000,2.700000,48,1,0,0
49,20.00,105.5,125.000000,5.700000,2.600000,49,1,0,0

In [13]:


# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(spline_interpolation["Resp"], spline_interpolation["SBP"],spline_interpolation["Platelets"], spline_interpolation["Bilirubin_total"], spline_interpolation["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
spline_interpolation['qSOFA']=result_qsofa
spline_interpolation['SOFA']=result_sofa

spline_interpolation

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.000000,101.000000,187.000000,2.300000,3.400000,1,0,0,0
2,20.000000,101.129061,177.601762,2.450080,3.532778,2,0,0,0
3,19.000000,107.160248,170.355512,2.570015,3.627850,3,0,0,0
4,24.000000,114.181947,165.004496,2.300000,3.400000,4,0,1,1
5,25.000000,114.409801,161.291957,2.730154,3.727437,5,0,1,1
6,26.000000,107.769502,158.961141,2.779020,3.745914,6,0,1,1
7,28.500000,107.322502,187.000000,2.700000,3.700000,7,0,1,1
8,24.250000,115.162551,157.413916,2.856813,3.764718,8,0,1,1
9,15.000000,120.497769,157.670453,2.904249,3.783247,9,0,0,0
10,25.000000,121.068575,158.257542,2.969718,3.819759,10,0,1,1
11,26.000000,121.039931,158.907863,3.061706,3.876747,11,0,1,1
12,26.460295,121.464126,158.000000,3.000000,3.800000,12,0,1,1
13,25.500000,121.728216,159.328917,3.311626,4.033962,13,0,1,1
14,19.000000,120.870128,158.566633,3.451941,4.124570,14,0,0,0
15,20.000000,118.750630,156.855255,3.590650,4.216764,15,0,0,0
16,20.500000,118.169633,154.047515,3.718869,4.305735,16,0,0,0
17,20.500000,120.142464,150.000000,3.827717,4.386288,17,0,0,0
18,21.500000,120.889981,159.000000,3.908309,4.300000,18,0,0,0
19,21.000000,118.615907,138.597544,3.951763,4.496106,19,0,0,0
20,18.000000,114.973019,132.310907,3.949197,4.513419,20,0,0,0
21,18.750000,111.137305,150.000000,3.900000,4.500000,21,0,0,0
22,24.000000,107.754131,121.545559,3.778075,4.484669,22,0,1,1
23,29.000000,101.000000,118.254534,3.629608,4.451986,23,0,1,1
24,28.000000,106.000000,116.815082,3.471946,4.416023,24,0,1,1
25,32.000000,115.500000,116.901910,3.330703,4.383462,25,0,1,1
26,23.000000,106.000000,119.000000,3.200000,4.400000,26,0,1,1
27,30.000000,118.000000,120.114984,3.199817,4.354462,27,0,1,1
28,25.000000,121.000000,122.471522,3.248015,4.370739,28,0,1,1
29,25.000000,121.500000,124.814921,3.362378,4.416008,29,0,1,1
30,26.000000,121.000000,126.761822,3.526149,4.496626,30,0,1,1
31,25.000000,118.000000,127.978273,3.722573,4.618917,31,0,1,1
32,30.000000,121.000000,126.000000,4.300000,4.600000,32,0,1,1
33,25.000000,117.000000,127.125730,4.146350,4.888523,33,0,1,1
34,22.750000,110.000000,124.515007,4.340225,4.901729,34,0,1,1
35,23.000000,107.000000,120.237054,4.505828,4.738850,35,0,1,1
36,24.000000,110.500000,124.000000,4.900000,4.700000,36,0,1,1
37,24.000000,97.000000,110.258551,4.762040,4.300000,37,0,1,1
38,21.000000,101.000000,106.878201,4.859989,3.816509,38,0,0,0
39,24.000000,107.500000,106.109611,4.942722,3.655146,39,0,1,1
40,24.000000,81.500000,106.000000,5.200000,3.600000,40,1,1,1
41,20.000000,90.000000,112.948196,5.076658,3.395757,41,1,1,1
42,20.000000,96.000000,118.832708,5.134772,3.279298,42,1,1,1
43,20.000000,93.000000,125.127827,5.191587,3.170800,43,1,1,1
44,20.000000,97.500000,130.908900,5.250562,3.069721,44,1,1,1
45,20.000000,110.000000,133.000000,5.700000,3.000000,45,1,0,0
46,20.000000,100.500000,137.443918,5.388937,2.886178,46,1,0,0
47,20.000000,104.500000,136.857345,5.475329,2.797097,47,1,0,0
48,20.000000,129.000000,132.907486,5.577852,2.703345,48,1,0,0
49,20.000000,105.500000,125.000000,5.700000,2.600000,49,1,0,0

In [16]:


# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
      
for a,b,c,d,e in zip(stine_interpolation["Resp"], stine_interpolation["SBP"],stine_interpolation["Platelets"], stine_interpolation["Bilirubin_total"], stine_interpolation["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
stine_interpolation['qSOFA']=result_qsofa
stine_interpolation['SOFA']=result_sofa

stine_interpolation

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.000000,101.0,187.000000,2.300000,3.400000,1,0,0,0
2,20.000000,101.0,187.000000,2.300000,3.400000,2,0,0,0
3,19.000000,101.0,187.000000,2.300000,3.400000,3,0,0,0
4,24.000000,101.0,187.000000,2.300000,3.400000,4,0,1,1
5,25.000000,101.0,187.000000,2.461953,3.539424,5,0,1,1
6,26.000000,101.0,187.000000,2.595286,3.639424,6,0,1,1
7,28.500000,101.0,187.000000,2.700000,3.700000,7,0,1,1
8,24.250000,101.0,176.939467,2.770478,3.728741,8,0,1,1
9,15.000000,101.0,169.009201,2.824087,3.743878,9,0,0,0
10,25.000000,101.0,163.209201,2.876650,3.756516,10,0,1,1
11,26.000000,101.0,159.539467,2.934324,3.773672,11,0,1,1
12,25.797991,101.0,158.000000,3.000000,3.800000,12,0,1,1
13,25.500000,101.0,157.781402,3.077519,3.864744,13,0,1,1
14,19.000000,101.0,157.997639,3.169007,3.955629,14,0,0,0
15,20.000000,101.0,158.500000,3.273348,4.050000,15,0,0,0
16,20.500000,101.0,159.075219,3.388850,4.140617,16,0,0,0
17,20.500000,101.0,159.406189,3.512810,4.224448,17,0,0,0
18,21.500000,101.0,159.000000,3.640635,4.300000,18,0,0,0
19,21.000000,101.0,156.657343,3.763840,4.370925,19,0,0,0
20,18.000000,101.0,153.436725,3.864810,4.440928,20,0,0,0
21,18.750000,101.0,150.000000,3.900000,4.500000,21,0,0,0
22,24.000000,101.0,145.270904,3.813863,4.494567,22,0,1,1
23,29.000000,101.0,138.446287,3.647040,4.466562,23,0,1,1
24,28.000000,106.0,130.403543,3.452850,4.434030,24,0,1,1
25,32.000000,115.5,122.777165,3.285479,4.409049,25,0,1,1
26,23.000000,106.0,119.000000,3.200000,4.400000,26,0,1,1
27,30.000000,118.0,119.636291,3.334602,4.423620,27,0,1,1
28,25.000000,121.0,120.897810,3.542006,4.461337,28,0,1,1
29,25.000000,121.5,122.500000,3.750000,4.500000,29,0,1,1
30,26.000000,121.0,124.126515,3.947548,4.536607,30,0,1,1
31,25.000000,118.0,125.424658,4.131329,4.570096,31,0,1,1
32,30.000000,121.0,126.000000,4.300000,4.600000,32,0,1,1
33,25.000000,117.0,125.927629,4.460167,4.627912,33,0,1,1
34,22.750000,110.0,125.569546,4.618014,4.655441,34,0,1,1
35,23.000000,107.0,124.926691,4.770128,4.681812,35,0,1,1
36,24.000000,110.5,124.000000,4.900000,4.700000,36,0,1,1
37,24.000000,97.0,120.806154,4.981211,4.300000,37,0,1,1
38,21.000000,101.0,115.000000,5.050000,4.012001,38,0,0,0
39,24.000000,107.5,109.153529,5.120915,3.780683,39,0,1,1
40,24.000000,81.5,106.000000,5.200000,3.600000,40,1,1,1
41,20.000000,90.0,108.400737,5.287442,3.458610,41,1,1,1
42,20.000000,96.0,115.301486,5.381163,3.334946,42,1,1,1
43,20.000000,93.0,123.697399,5.481163,3.219449,43,1,1,1
44,20.000000,97.5,130.592569,5.587442,3.108387,44,1,1,1
45,20.000000,110.0,133.000000,5.700000,3.000000,45,1,0,0
46,20.000000,100.5,131.877587,5.700000,2.894549,46,1,0,0
47,20.000000,104.5,130.170116,5.700000,2.792861,47,1,0,0
48,20.000000,129.0,127.877587,5.700000,2.694740,48,1,0,0
49,20.000000,105.5,125.000000,5.700000,2.600000,49,1,0,0

In [17]:
i=nandf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
j=linear_interpolation[['SepsisLabel','ICULOS','qSOFA','SOFA']]
k=spline_interpolation[['SepsisLabel','ICULOS','qSOFA','SOFA']]
l=stine_interpolation[['SepsisLabel','ICULOS','qSOFA','SOFA']]

In [18]:
df_all = pd.concat([i.set_index('ICULOS'),j.set_index('ICULOS'),k.set_index('ICULOS'), l.set_index('ICULOS') ], 
                   axis='columns', keys=['with_nan', 'linear_interpolation', "spline_interpolation", "stine_interpolation"])
df_all

          with_nan            linear_interpolation             \
       SepsisLabel qSOFA SOFA          SepsisLabel qSOFA SOFA
ICULOS
1                0     0    0                    0     0    0
2                0     0    0                    0     0    0
3                0     0    0                    0     0    0
4                0     1    1                    0     1    1
5                0     1    0                    0     1    1
6                0     1    0                    0     1    1
7                0     1    1                    0     1    1
8                0     1    0                    0     1    1
9                0     0    0                    0     0    0
10               0     1    0                    0     1    1
11               0     1    0                    0     1    1
12               0     0    0                    0     1    1
13               0     1    0                    0     1    1
14               0     0    0                    0     0    0
15               0     0    0                    0     0    0
16               0     0    0                    0     0    0
17               0     0    0                    0     0    0
18               0     0    0                    0     0    0
19               0     0    0                    0     0    0
20               0     0    0                    0     0    0
21               0     0    0                    0     0    0
22               0     1    0                    0     1    1
23               0     1    0                    0     1    1
24               0     1    0                    0     1    1
25               0     1    0                    0     1    1
26               0     1    1                    0     1    1
27               0     1    0                    0     1    1
28               0     1    0                    0     1    1
29               0     1    0                    0     1    1
30               0     1    0                    0     1    1
31               0     1    0                    0     1    1
32               0     1    1                    0     1    1
33               0     1    0                    0     1    1
34               0     1    0                    0     1    1
35               0     1    0                    0     1    1
36               0     1    1                    0     1    1
37               0     1    1                    0     1    1
38               0     0    0                    0     0    0
39               0     1    0                    0     1    1
40               1     1    1                    1     1    1
41               1     1    0                    1     1    1
42               1     1    0                    1     1    1
43               1     1    0                    1     1    1
44               1     1    0                    1     1    1
45               1     0    0                    1     0    0
46               1     0    0                    1     0    0
47               1     0    0                    1     0    0
48               1     0    0                    1     0    0
49               1     0    0                    1     0    0

       spline_interpolation            stine_interpolation
                SepsisLabel qSOFA SOFA         SepsisLabel qSOFA SOFA
ICULOS
1                         0     0    0                   0     0    0
2                         0     0    0                   0     0    0
3                         0     0    0                   0     0    0
4                         0     1    1                   0     1    1
5                         0     1    1                   0     1    1
6                         0     1    1                   0     1    1
7                         0     1    1                   0     1    1
8                         0     1    1                   0     1    1
9                         0     0    0                   0     0    0
10                        0     1    1                   0     1    1
11                        0     1    1                   0     1    1
12                        0     1    1                   0     1    1
13                        0     1    1                   0     1    1
14                        0     0    0                   0     0    0
15                        0     0    0                   0     0    0
16                        0     0    0                   0     0    0
17                        0     0    0                   0     0    0
18                        0     0    0                   0     0    0
19                        0     0    0                   0     0    0
20                        0     0    0                   0     0    0
21                        0     0    0                   0     0    0
22                        0     1    1                   0     1    1
23                        0     1    1                   0     1    1
24                        0     1    1                   0     1    1
25                        0     1    1                   0     1    1
26                        0     1    1                   0     1    1
27                        0     1    1                   0     1    1
28                        0     1    1                   0     1    1
29                        0     1    1                   0     1    1
30                        0     1    1                   0     1    1
31                        0     1    1                   0     1    1
32                        0     1    1                   0     1    1
33                        0     1    1                   0     1    1
34                        0     1    1                   0     1    1
35                        0     1    1                   0     1    1
36                        0     1    1                   0     1    1
37                        0     1    1                   0     1    1
38                        0     0    0                   0     0    0
39                        0     1    1                   0     1    1
40                        1     1    1                   1     1    1
41                        1     1    1                   1     1    1
42                        1     1    1                   1     1    1
43                        1     1    1                   1     1    1
44                        1     1    1                   1     1    1
45                        1     0    0                   1     0    0
46                        1     0    0                   1     0    0
47                        1     0    0                   1     0    0
48                        1     0    0                   1     0    0
49                        1     0    0                   1     0    0

In [19]:
# imputation with KalmanSmoother and state space representation of arima model na_kalman(x)

na_kalman=pd.read_table("p015036_sepsis_na_kalman_state_space.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_kalman["Resp"], na_kalman["SBP"], na_kalman["Platelets"], na_kalman["Bilirubin_total"], na_kalman["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_kalman['qSOFA']=result_qsofa
na_kalman['SOFA']=result_sofa

na_kalman

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.00,101.0,187.000000,2.300000,3.400000,1,0,0,0
2,20.00,101.0,187.000000,2.300000,3.400000,2,0,0,0
3,19.00,101.0,187.000000,2.300000,3.400000,3,0,0,0
4,24.00,101.0,187.000000,2.300000,3.400000,4,0,1,1
5,25.00,101.0,187.000000,2.433333,3.500000,5,0,1,1
6,26.00,101.0,187.000000,2.566667,3.600000,6,0,1,1
7,28.50,101.0,187.000000,2.700000,3.700000,7,0,1,1
8,24.25,101.0,181.200000,2.760000,3.720000,8,0,1,1
9,15.00,101.0,175.400000,2.820000,3.740000,9,0,0,0
10,25.00,101.0,169.600000,2.880000,3.760000,10,0,1,1
11,26.00,101.0,163.800000,2.940000,3.780000,11,0,1,1
12,25.75,101.0,158.000000,3.000000,3.800000,12,0,1,1
13,25.50,101.0,158.166667,3.100000,3.883333,13,0,1,1
14,19.00,101.0,158.333333,3.200000,3.966667,14,0,0,0
15,20.00,101.0,158.500000,3.300000,4.050000,15,0,0,0
16,20.50,101.0,158.666667,3.400000,4.133333,16,0,0,0
17,20.50,101.0,158.833333,3.500000,4.216667,17,0,0,0
18,21.50,101.0,159.000000,3.600000,4.300000,18,0,0,0
19,21.00,101.0,156.000000,3.700000,4.366667,19,0,0,0
20,18.00,101.0,153.000000,3.800000,4.433333,20,0,0,0
21,18.75,101.0,150.000000,3.900000,4.500000,21,0,0,0
22,24.00,101.0,143.800000,3.760000,4.480000,22,0,1,1
23,29.00,101.0,137.600000,3.620000,4.460000,23,0,1,1
24,28.00,106.0,131.400000,3.480000,4.440000,24,0,1,1
25,32.00,115.5,125.200000,3.340000,4.420000,25,0,1,1
26,23.00,106.0,119.000000,3.200000,4.400000,26,0,1,1
27,30.00,118.0,120.166667,3.383333,4.433333,27,0,1,1
28,25.00,121.0,121.333333,3.566667,4.466667,28,0,1,1
29,25.00,121.5,122.500000,3.750000,4.500000,29,0,1,1
30,26.00,121.0,123.666667,3.933333,4.533333,30,0,1,1
31,25.00,118.0,124.833333,4.116667,4.566667,31,0,1,1
32,30.00,121.0,126.000000,4.300000,4.600000,32,0,1,1
33,25.00,117.0,125.500000,4.450000,4.625000,33,0,1,1
34,22.75,110.0,125.000000,4.600000,4.650000,34,0,1,1
35,23.00,107.0,124.500000,4.750000,4.675000,35,0,1,1
36,24.00,110.5,124.000000,4.900000,4.700000,36,0,1,1
37,24.00,97.0,119.500000,4.975000,4.300000,37,0,1,1
38,21.00,101.0,115.000000,5.050000,4.066667,38,0,0,0
39,24.00,107.5,110.500000,5.125000,3.833333,39,0,1,1
40,24.00,81.5,106.000000,5.200000,3.600000,40,1,1,1
41,20.00,90.0,111.400000,5.300000,3.480000,41,1,1,1
42,20.00,96.0,116.800000,5.400000,3.360000,42,1,1,1
43,20.00,93.0,122.200000,5.500000,3.240000,43,1,1,1
44,20.00,97.5,127.600000,5.600000,3.120000,44,1,1,1
45,20.00,110.0,133.000000,5.700000,3.000000,45,1,0,0
46,20.00,100.5,131.000000,5.700000,2.900000,46,1,0,0
47,20.00,104.5,129.000000,5.700000,2.800000,47,1,0,0
48,20.00,129.0,127.000000,5.700000,2.700000,48,1,0,0
49,20.00,105.5,125.000000,5.700000,2.600000,49,1,0,0

In [24]:
na_kalman_StructTS=pd.read_table("p015036_sepsis_na_kalman_StructTS.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_kalman_StructTS["Resp"], na_kalman_StructTS["SBP"], na_kalman_StructTS["Platelets"], na_kalman_StructTS["Bilirubin_total"], na_kalman_StructTS["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_kalman_StructTS['qSOFA']=result_qsofa
na_kalman_StructTS['SOFA']=result_sofa

na_kalman_StructTS

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.255319,101.216394,185.688420,2.300000,3.407804,1,0,0,0
2,20.000000,101.377825,184.947322,2.300000,3.412080,2,0,0,0
3,19.000000,101.539255,184.206224,2.300000,3.419624,3,0,0,0
4,24.000000,101.700685,183.465126,2.300000,3.400000,4,0,1,1
5,25.000000,101.862116,182.724028,2.433333,3.508794,5,0,1,1
6,26.000000,102.023546,181.982930,2.566667,3.589624,6,0,1,1
7,28.500000,102.184976,187.000000,2.700000,3.700000,7,0,1,1
8,24.250000,102.346406,177.571731,2.760000,3.699844,8,0,1,1
9,15.000000,102.507837,173.901630,2.820000,3.728203,9,0,0,0
10,25.000000,102.669267,170.231529,2.880000,3.757687,10,0,1,1
11,26.000000,102.830697,166.561428,2.940000,3.788778,11,0,1,1
12,23.361810,102.992128,158.000000,3.000000,3.800000,12,0,1,1
13,25.500000,103.153558,161.709293,3.100000,3.900996,13,0,1,1
14,19.000000,103.314988,160.527259,3.200000,3.981516,14,0,0,0
15,20.000000,103.476419,159.345225,3.300000,4.062427,15,0,0,0
16,20.500000,103.637849,158.163192,3.400000,4.142640,16,0,0,0
17,20.500000,103.799279,156.981158,3.500000,4.221064,17,0,0,0
18,21.500000,103.960709,159.000000,3.600000,4.300000,18,0,0,0
19,21.000000,104.122140,152.988904,3.700000,4.361503,19,0,0,0
20,18.000000,104.283570,150.178683,3.800000,4.421581,20,0,0,0
21,18.750000,104.445000,150.000000,3.900000,4.500000,21,0,0,0
22,24.000000,104.606431,143.219660,3.760000,4.476584,22,0,1,1
23,29.000000,101.000000,139.070857,3.620000,4.471532,23,0,1,1
24,28.000000,106.000000,134.922054,3.480000,4.461712,24,0,1,1
25,32.000000,115.500000,130.773251,3.340000,4.447996,25,0,1,1
26,23.000000,106.000000,119.000000,3.200000,4.400000,26,0,1,1
27,30.000000,118.000000,126.353968,3.383333,4.473982,27,0,1,1
28,25.000000,121.000000,126.083487,3.566667,4.513188,28,0,1,1
29,25.000000,121.500000,125.813007,3.750000,4.547506,29,0,1,1
30,26.000000,121.000000,125.542527,3.933333,4.575572,30,0,1,1
31,25.000000,118.000000,125.272046,4.116667,4.596019,31,0,1,1
32,30.000000,121.000000,126.000000,4.300000,4.600000,32,0,1,1
33,25.000000,117.000000,124.223213,4.450000,4.623335,33,0,1,1
34,22.750000,110.000000,123.444860,4.600000,4.626937,34,0,1,1
35,23.000000,107.000000,122.666506,4.750000,4.616384,35,0,1,1
36,24.000000,110.500000,124.000000,4.900000,4.700000,36,0,1,1
37,24.000000,97.000000,120.035568,4.975000,4.300000,37,0,1,1
38,21.000000,101.000000,118.182984,5.050000,4.109031,38,0,0,0
39,24.000000,107.500000,116.330399,5.125000,3.882190,39,0,1,1
40,24.000000,81.500000,106.000000,5.200000,3.600000,40,1,1,1
41,20.000000,90.000000,116.937633,5.300000,3.521805,41,1,1,1
42,20.000000,96.000000,119.397452,5.400000,3.392567,42,1,1,1
43,20.000000,93.000000,121.857271,5.500000,3.263964,43,1,1,1
44,20.000000,97.500000,124.317090,5.600000,3.136311,44,1,1,1
45,20.000000,110.000000,133.000000,5.700000,3.000000,45,1,0,0
46,20.000000,100.500000,126.071232,5.770833,2.904679,46,1,0,0
47,20.000000,104.500000,125.365555,5.841667,2.800621,47,1,0,0
48,20.000000,129.000000,124.659879,5.912500,2.697353,48,1,0,0
49,20.000000,105.500000,125.000000,5.983333,2.600000,49,1,0,0

In [25]:
i=nandf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
j=linear_interpolation[['SepsisLabel','ICULOS','qSOFA','SOFA']]
z=na_kalman[['SepsisLabel','ICULOS','qSOFA','SOFA']]
kk=na_kalman_StructTS[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nan_interpolation_kalman_kalmanStructTS = pd.concat([i.set_index('ICULOS'),j.set_index('ICULOS'), z.set_index('ICULOS'), kk.set_index('ICULOS')], 
                   axis='columns', keys=[ "with_nan", "linear_interpolation", "na_kalman", "na_kalman_StructTS"])

In [26]:
nan_interpolation_kalman_kalmanStructTS

          with_nan            linear_interpolation              na_kalman  \
       SepsisLabel qSOFA SOFA          SepsisLabel qSOFA SOFA SepsisLabel
ICULOS
1                0     0    0                    0     0    0           0
2                0     0    0                    0     0    0           0
3                0     0    0                    0     0    0           0
4                0     1    1                    0     1    1           0
5                0     1    0                    0     1    1           0
6                0     1    0                    0     1    1           0
7                0     1    1                    0     1    1           0
8                0     1    0                    0     1    1           0
9                0     0    0                    0     0    0           0
10               0     1    0                    0     1    1           0
11               0     1    0                    0     1    1           0
12               0     0    0                    0     1    1           0
13               0     1    0                    0     1    1           0
14               0     0    0                    0     0    0           0
15               0     0    0                    0     0    0           0
16               0     0    0                    0     0    0           0
17               0     0    0                    0     0    0           0
18               0     0    0                    0     0    0           0
19               0     0    0                    0     0    0           0
20               0     0    0                    0     0    0           0
21               0     0    0                    0     0    0           0
22               0     1    0                    0     1    1           0
23               0     1    0                    0     1    1           0
24               0     1    0                    0     1    1           0
25               0     1    0                    0     1    1           0
26               0     1    1                    0     1    1           0
27               0     1    0                    0     1    1           0
28               0     1    0                    0     1    1           0
29               0     1    0                    0     1    1           0
30               0     1    0                    0     1    1           0
31               0     1    0                    0     1    1           0
32               0     1    1                    0     1    1           0
33               0     1    0                    0     1    1           0
34               0     1    0                    0     1    1           0
35               0     1    0                    0     1    1           0
36               0     1    1                    0     1    1           0
37               0     1    1                    0     1    1           0
38               0     0    0                    0     0    0           0
39               0     1    0                    0     1    1           0
40               1     1    1                    1     1    1           1
41               1     1    0                    1     1    1           1
42               1     1    0                    1     1    1           1
43               1     1    0                    1     1    1           1
44               1     1    0                    1     1    1           1
45               1     0    0                    1     0    0           1
46               1     0    0                    1     0    0           1
47               1     0    0                    1     0    0           1
48               1     0    0                    1     0    0           1
49               1     0    0                    1     0    0           1

                  na_kalman_StructTS
       qSOFA SOFA        SepsisLabel qSOFA SOFA
ICULOS
1          0    0                  0     0    0
2          0    0                  0     0    0
3          0    0                  0     0    0
4          1    1                  0     1    1
5          1    1                  0     1    1
6          1    1                  0     1    1
7          1    1                  0     1    1
8          1    1                  0     1    1
9          0    0                  0     0    0
10         1    1                  0     1    1
11         1    1                  0     1    1
12         1    1                  0     1    1
13         1    1                  0     1    1
14         0    0                  0     0    0
15         0    0                  0     0    0
16         0    0                  0     0    0
17         0    0                  0     0    0
18         0    0                  0     0    0
19         0    0                  0     0    0
20         0    0                  0     0    0
21         0    0                  0     0    0
22         1    1                  0     1    1
23         1    1                  0     1    1
24         1    1                  0     1    1
25         1    1                  0     1    1
26         1    1                  0     1    1
27         1    1                  0     1    1
28         1    1                  0     1    1
29         1    1                  0     1    1
30         1    1                  0     1    1
31         1    1                  0     1    1
32         1    1                  0     1    1
33         1    1                  0     1    1
34         1    1                  0     1    1
35         1    1                  0     1    1
36         1    1                  0     1    1
37         1    1                  0     1    1
38         0    0                  0     0    0
39         1    1                  0     1    1
40         1    1                  1     1    1
41         1    1                  1     1    1
42         1    1                  1     1    1
43         1    1                  1     1    1
44         1    1                  1     1    1
45         0    0                  1     0    0
46         0    0                  1     0    0
47         0    0                  1     0    0
48         0    0                  1     0    0
49         0    0                  1     0    0

# na_locf and nocb

In [27]:
# Last Observation Carried Forward (locf)


locf=pd.read_table("p015036_sepsis_na_locf.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(locf["Resp"], locf["SBP"], locf["Platelets"], locf["Bilirubin_total"], locf["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
locf['qSOFA']=result_qsofa
locf['SOFA']=result_sofa

locf

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.00,101.0,187,2.3,3.4,1,0,0,0
2,20.00,101.0,187,2.3,3.4,2,0,0,0
3,19.00,101.0,187,2.3,3.4,3,0,0,0
4,24.00,101.0,187,2.3,3.4,4,0,1,1
5,25.00,101.0,187,2.3,3.4,5,0,1,1
6,26.00,101.0,187,2.3,3.4,6,0,1,1
7,28.50,101.0,187,2.7,3.7,7,0,1,1
8,24.25,101.0,187,2.7,3.7,8,0,1,1
9,15.00,101.0,187,2.7,3.7,9,0,0,0
10,25.00,101.0,187,2.7,3.7,10,0,1,1
11,26.00,101.0,187,2.7,3.7,11,0,1,1
12,26.00,101.0,158,3.0,3.8,12,0,1,1
13,25.50,101.0,158,3.0,3.8,13,0,1,1
14,19.00,101.0,158,3.0,3.8,14,0,0,0
15,20.00,101.0,158,3.0,3.8,15,0,0,0
16,20.50,101.0,158,3.0,3.8,16,0,0,0
17,20.50,101.0,158,3.0,3.8,17,0,0,0
18,21.50,101.0,159,3.0,4.3,18,0,0,0
19,21.00,101.0,159,3.0,4.3,19,0,0,0
20,18.00,101.0,159,3.0,4.3,20,0,0,0
21,18.75,101.0,150,3.9,4.5,21,0,0,0
22,24.00,101.0,150,3.9,4.5,22,0,1,1
23,29.00,101.0,150,3.9,4.5,23,0,1,1
24,28.00,106.0,150,3.9,4.5,24,0,1,1
25,32.00,115.5,150,3.9,4.5,25,0,1,1
26,23.00,106.0,119,3.2,4.4,26,0,1,1
27,30.00,118.0,119,3.2,4.4,27,0,1,1
28,25.00,121.0,119,3.2,4.4,28,0,1,1
29,25.00,121.5,119,3.2,4.4,29,0,1,1
30,26.00,121.0,119,3.2,4.4,30,0,1,1
31,25.00,118.0,119,3.2,4.4,31,0,1,1
32,30.00,121.0,126,4.3,4.6,32,0,1,1
33,25.00,117.0,126,4.3,4.6,33,0,1,1
34,22.75,110.0,126,4.3,4.6,34,0,1,1
35,23.00,107.0,126,4.3,4.6,35,0,1,1
36,24.00,110.5,124,4.9,4.7,36,0,1,1
37,24.00,97.0,124,4.9,4.3,37,0,1,1
38,21.00,101.0,124,4.9,4.3,38,0,0,0
39,24.00,107.5,124,4.9,4.3,39,0,1,1
40,24.00,81.5,106,5.2,3.6,40,1,1,1
41,20.00,90.0,106,5.2,3.6,41,1,1,1
42,20.00,96.0,106,5.2,3.6,42,1,1,1
43,20.00,93.0,106,5.2,3.6,43,1,1,1
44,20.00,97.5,106,5.2,3.6,44,1,1,1
45,20.00,110.0,133,5.7,3.0,45,1,0,0
46,20.00,100.5,133,5.7,3.0,46,1,0,0
47,20.00,104.5,133,5.7,3.0,47,1,0,0
48,20.00,129.0,133,5.7,3.0,48,1,0,0
49,20.00,105.5,125,5.7,2.6,49,1,0,0

In [28]:
# Next Observation Carried Backward (nocb) 

nocb=pd.read_table("p015036_sepsis_na_nocb.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(nocb["Resp"], nocb["SBP"], nocb["Platelets"], nocb["Bilirubin_total"], nocb["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
nocb['qSOFA']=result_qsofa
nocb['SOFA']=result_sofa

nocb

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.00,101.0,187,2.3,3.4,1,0,0,0
2,20.00,101.0,187,2.3,3.4,2,0,0,0
3,19.00,101.0,187,2.3,3.4,3,0,0,0
4,24.00,101.0,187,2.3,3.4,4,0,1,1
5,25.00,101.0,187,2.7,3.7,5,0,1,1
6,26.00,101.0,187,2.7,3.7,6,0,1,1
7,28.50,101.0,187,2.7,3.7,7,0,1,1
8,24.25,101.0,158,3.0,3.8,8,0,1,1
9,15.00,101.0,158,3.0,3.8,9,0,0,0
10,25.00,101.0,158,3.0,3.8,10,0,1,1
11,26.00,101.0,158,3.0,3.8,11,0,1,1
12,25.50,101.0,158,3.0,3.8,12,0,1,1
13,25.50,101.0,159,3.9,4.3,13,0,1,1
14,19.00,101.0,159,3.9,4.3,14,0,0,0
15,20.00,101.0,159,3.9,4.3,15,0,0,0
16,20.50,101.0,159,3.9,4.3,16,0,0,0
17,20.50,101.0,159,3.9,4.3,17,0,0,0
18,21.50,101.0,159,3.9,4.3,18,0,0,0
19,21.00,101.0,150,3.9,4.5,19,0,0,0
20,18.00,101.0,150,3.9,4.5,20,0,0,0
21,18.75,101.0,150,3.9,4.5,21,0,0,0
22,24.00,101.0,119,3.2,4.4,22,0,1,1
23,29.00,101.0,119,3.2,4.4,23,0,1,1
24,28.00,106.0,119,3.2,4.4,24,0,1,1
25,32.00,115.5,119,3.2,4.4,25,0,1,1
26,23.00,106.0,119,3.2,4.4,26,0,1,1
27,30.00,118.0,126,4.3,4.6,27,0,1,1
28,25.00,121.0,126,4.3,4.6,28,0,1,1
29,25.00,121.5,126,4.3,4.6,29,0,1,1
30,26.00,121.0,126,4.3,4.6,30,0,1,1
31,25.00,118.0,126,4.3,4.6,31,0,1,1
32,30.00,121.0,126,4.3,4.6,32,0,1,1
33,25.00,117.0,124,4.9,4.7,33,0,1,1
34,22.75,110.0,124,4.9,4.7,34,0,1,1
35,23.00,107.0,124,4.9,4.7,35,0,1,1
36,24.00,110.5,124,4.9,4.7,36,0,1,1
37,24.00,97.0,106,5.2,4.3,37,0,1,1
38,21.00,101.0,106,5.2,3.6,38,0,0,0
39,24.00,107.5,106,5.2,3.6,39,0,1,1
40,24.00,81.5,106,5.2,3.6,40,1,1,1
41,20.00,90.0,133,5.7,3.0,41,1,1,1
42,20.00,96.0,133,5.7,3.0,42,1,1,1
43,20.00,93.0,133,5.7,3.0,43,1,1,1
44,20.00,97.5,133,5.7,3.0,44,1,1,1
45,20.00,110.0,133,5.7,3.0,45,1,0,0
46,20.00,100.5,125,5.7,2.6,46,1,0,0
47,20.00,104.5,125,5.7,2.6,47,1,0,0
48,20.00,129.0,125,5.7,2.6,48,1,0,0
49,20.00,105.5,125,5.7,2.6,49,1,0,0

In [29]:


i=nandf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
zx=locf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
kf=nocb[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nan_locf_nocb = pd.concat([i.set_index('ICULOS'), zx.set_index('ICULOS'), kf.set_index('ICULOS')], 
                   axis='columns', keys=[ "with_nan", "locf", "nocb"])

In [30]:
nan_locf_nocb

          with_nan                   locf                   nocb
       SepsisLabel qSOFA SOFA SepsisLabel qSOFA SOFA SepsisLabel qSOFA SOFA
ICULOS
1                0     0    0           0     0    0           0     0    0
2                0     0    0           0     0    0           0     0    0
3                0     0    0           0     0    0           0     0    0
4                0     1    1           0     1    1           0     1    1
5                0     1    0           0     1    1           0     1    1
6                0     1    0           0     1    1           0     1    1
7                0     1    1           0     1    1           0     1    1
8                0     1    0           0     1    1           0     1    1
9                0     0    0           0     0    0           0     0    0
10               0     1    0           0     1    1           0     1    1
11               0     1    0           0     1    1           0     1    1
12               0     0    0           0     1    1           0     1    1
13               0     1    0           0     1    1           0     1    1
14               0     0    0           0     0    0           0     0    0
15               0     0    0           0     0    0           0     0    0
16               0     0    0           0     0    0           0     0    0
17               0     0    0           0     0    0           0     0    0
18               0     0    0           0     0    0           0     0    0
19               0     0    0           0     0    0           0     0    0
20               0     0    0           0     0    0           0     0    0
21               0     0    0           0     0    0           0     0    0
22               0     1    0           0     1    1           0     1    1
23               0     1    0           0     1    1           0     1    1
24               0     1    0           0     1    1           0     1    1
25               0     1    0           0     1    1           0     1    1
26               0     1    1           0     1    1           0     1    1
27               0     1    0           0     1    1           0     1    1
28               0     1    0           0     1    1           0     1    1
29               0     1    0           0     1    1           0     1    1
30               0     1    0           0     1    1           0     1    1
31               0     1    0           0     1    1           0     1    1
32               0     1    1           0     1    1           0     1    1
33               0     1    0           0     1    1           0     1    1
34               0     1    0           0     1    1           0     1    1
35               0     1    0           0     1    1           0     1    1
36               0     1    1           0     1    1           0     1    1
37               0     1    1           0     1    1           0     1    1
38               0     0    0           0     0    0           0     0    0
39               0     1    0           0     1    1           0     1    1
40               1     1    1           1     1    1           1     1    1
41               1     1    0           1     1    1           1     1    1
42               1     1    0           1     1    1           1     1    1
43               1     1    0           1     1    1           1     1    1
44               1     1    0           1     1    1           1     1    1
45               1     0    0           1     0    0           1     0    0
46               1     0    0           1     0    0           1     0    0
47               1     0    0           1     0    0           1     0    0
48               1     0    0           1     0    0           1     0    0
49               1     0    0           1     0    0           1     0    0

In [33]:

na_ma=pd.read_table("p015036_sepsis_na_ma.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_ma["Resp"], na_ma["SBP"], na_ma["Platelets"], na_ma["Bilirubin_total"], na_ma["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_ma['qSOFA']=result_qsofa
na_ma['SOFA']=result_sofa

na_ma

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,22.00000,103.500,172.500000,2.500000,3.550000,1,0,1,1
2,20.00000,103.500,172.500000,2.500000,3.550000,2,0,0,0
3,19.00000,103.500,172.500000,2.500000,3.550000,3,0,0,0
4,24.00000,103.500,172.500000,2.300000,3.400000,4,0,1,1
5,25.00000,103.500,172.500000,2.500000,3.550000,5,0,1,1
6,26.00000,103.500,172.500000,2.500000,3.550000,6,0,1,1
7,28.50000,103.500,187.000000,2.700000,3.700000,7,0,1,1
8,24.25000,103.500,172.500000,2.666667,3.633333,8,0,1,1
9,15.00000,103.500,172.500000,2.850000,3.750000,9,0,0,0
10,25.00000,103.500,172.500000,2.850000,3.750000,10,0,1,1
11,26.00000,103.500,172.500000,2.850000,3.750000,11,0,1,1
12,21.90625,103.500,158.000000,3.000000,3.800000,12,0,0,0
13,25.50000,103.500,158.500000,2.850000,4.050000,13,0,1,1
14,19.00000,103.500,158.500000,3.200000,4.050000,14,0,0,0
15,20.00000,103.500,158.500000,3.450000,4.050000,15,0,0,0
16,20.50000,103.500,158.500000,3.450000,4.050000,16,0,0,0
17,20.50000,103.500,154.500000,3.450000,4.400000,17,0,0,0
18,21.50000,103.500,159.000000,3.450000,4.300000,18,0,0,0
19,21.00000,103.500,154.500000,3.366667,4.400000,19,0,0,0
20,18.00000,103.500,154.500000,3.550000,4.400000,20,0,0,0
21,18.75000,107.500,150.000000,3.900000,4.500000,21,0,0,0
22,24.00000,107.125,142.666667,3.550000,4.400000,22,0,1,1
23,29.00000,101.000,134.500000,3.550000,4.450000,23,0,1,1
24,28.00000,106.000,134.500000,3.550000,4.450000,24,0,1,1
25,32.00000,115.500,134.500000,3.550000,4.450000,25,0,1,1
26,23.00000,106.000,119.000000,3.200000,4.400000,26,0,1,1
27,30.00000,118.000,122.500000,3.750000,4.500000,27,0,1,1
28,25.00000,121.000,122.500000,3.750000,4.500000,28,0,1,1
29,25.00000,121.500,122.500000,3.750000,4.500000,29,0,1,1
30,26.00000,121.000,122.500000,3.750000,4.500000,30,0,1,1
31,25.00000,118.000,123.000000,4.133333,4.566667,31,0,1,1
32,30.00000,121.000,126.000000,4.300000,4.600000,32,0,1,1
33,25.00000,117.000,125.000000,4.600000,4.533333,33,0,1,1
34,22.75000,110.000,125.000000,4.600000,4.533333,34,0,1,1
35,23.00000,107.000,125.000000,4.600000,4.533333,35,0,1,1
36,24.00000,110.500,124.000000,4.900000,4.700000,36,0,1,1
37,24.00000,97.000,115.000000,5.050000,4.300000,37,0,1,1
38,21.00000,101.000,115.000000,5.050000,4.200000,38,0,0,0
39,24.00000,107.500,115.000000,5.050000,4.200000,39,0,1,1
40,24.00000,81.500,106.000000,5.200000,3.600000,40,1,1,1
41,20.00000,90.000,119.500000,5.450000,3.633333,41,1,1,1
42,20.00000,96.000,119.500000,5.450000,3.300000,42,1,1,1
43,20.00000,93.000,119.500000,5.450000,3.300000,43,1,1,1
44,20.00000,97.500,119.500000,5.450000,3.300000,44,1,1,1
45,20.00000,110.000,133.000000,5.700000,3.000000,45,1,0,0
46,20.00000,100.500,129.000000,5.450000,2.800000,46,1,0,0
47,20.00000,104.500,129.000000,5.450000,2.800000,47,1,0,0
48,20.00000,129.000,129.000000,5.450000,2.800000,48,1,0,0
49,20.00000,105.500,125.000000,5.450000,2.600000,49,1,0,0

In [34]:


na_ma_exponential=pd.read_table("p015036_sepsis_na_ma_exponential.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_ma_exponential["Resp"], na_ma_exponential["SBP"], na_ma_exponential["Platelets"], na_ma_exponential["Bilirubin_total"], na_ma_exponential["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_ma_exponential['qSOFA']=result_qsofa
na_ma_exponential['SOFA']=result_sofa

na_ma_exponential

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,20.600,102.666667,186.121212,2.344444,3.433333,1,0,0,0
2,20.000,102.666667,186.121212,2.344444,3.433333,2,0,0,0
3,19.000,102.666667,186.121212,2.344444,3.433333,3,0,0,0
4,24.000,102.666667,186.121212,2.300000,3.400000,4,0,1,1
5,25.000,102.666667,186.121212,2.433333,3.500000,5,0,1,1
6,26.000,102.666667,186.121212,2.566667,3.600000,6,0,1,1
7,28.500,102.666667,187.000000,2.700000,3.700000,7,0,1,1
8,24.250,102.666667,183.777778,2.690000,3.680000,8,0,1,1
9,15.000,102.666667,177.333333,2.800000,3.733333,9,0,0,0
10,25.000,102.666667,167.666667,2.900000,3.766667,10,0,1,1
11,26.000,102.666667,161.222222,2.966667,3.788889,11,0,1,1
12,23.425,102.666667,158.000000,3.000000,3.800000,12,0,1,1
13,25.500,102.666667,158.058824,2.990909,3.829412,13,0,1,1
14,19.000,102.666667,158.200000,3.017647,3.900000,14,0,0,0
15,20.000,102.666667,158.500000,3.100000,4.050000,15,0,0,0
16,20.500,102.666667,158.800000,3.300000,4.200000,16,0,0,0
17,20.500,102.666667,158.000000,3.600000,4.322222,17,0,0,0
18,21.500,102.666667,159.000000,3.800000,4.300000,18,0,0,0
19,21.000,102.666667,156.000000,3.852941,4.366667,19,0,0,0
20,18.000,102.666667,153.000000,3.878788,4.433333,20,0,0,0
21,18.750,104.500000,150.000000,3.900000,4.500000,21,0,0,0
22,24.000,104.600000,147.800000,3.822222,4.470000,22,0,1,1
23,29.000,101.000000,139.666667,3.666667,4.466667,23,0,1,1
24,28.000,106.000000,129.333333,3.433333,4.433333,24,0,1,1
25,32.000,115.500000,122.444444,3.277778,4.411111,25,0,1,1
26,23.000,106.000000,119.000000,3.200000,4.400000,26,0,1,1
27,30.000,118.000000,119.411765,3.264706,4.411765,27,0,1,1
28,25.000,121.000000,120.400000,3.420000,4.440000,28,0,1,1
29,25.000,121.500000,122.500000,3.750000,4.500000,29,0,1,1
30,26.000,121.000000,124.600000,4.080000,4.560000,30,0,1,1
31,25.000,118.000000,125.500000,4.272222,4.594444,31,0,1,1
32,30.000,121.000000,126.000000,4.300000,4.600000,32,0,1,1
33,25.000,117.000000,125.600000,4.420000,4.590909,33,0,1,1
34,22.750,110.000000,125.000000,4.600000,4.580000,34,0,1,1
35,23.000,107.000000,124.400000,4.780000,4.571429,35,0,1,1
36,24.000,110.500000,124.000000,4.900000,4.700000,36,0,1,1
37,24.000,97.000000,120.400000,4.960000,4.300000,37,0,1,1
38,21.000,101.000000,115.000000,5.050000,4.225000,38,0,0,0
39,24.000,107.500000,109.600000,5.140000,3.957143,39,0,1,1
40,24.000,81.500000,106.000000,5.200000,3.600000,40,1,1,1
41,20.000,90.000000,109.000000,5.255556,3.610000,41,1,1,1
42,20.000,96.000000,115.000000,5.366667,3.400000,42,1,1,1
43,20.000,93.000000,124.000000,5.533333,3.200000,43,1,1,1
44,20.000,97.500000,130.000000,5.644444,3.066667,44,1,1,1
45,20.000,110.000000,133.000000,5.700000,3.000000,45,1,0,0
46,20.000,100.500000,131.400000,5.684848,2.920000,46,1,0,0
47,20.000,104.500000,129.000000,5.684848,2.800000,47,1,0,0
48,20.000,129.000000,126.600000,5.684848,2.680000,48,1,0,0
49,20.000,105.500000,125.000000,5.684848,2.600000,49,1,0,0

In [36]:
i=nandf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nam=na_ma[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nae=na_ma_exponential[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nan_na_ma_na_exponential = pd.concat([i.set_index('ICULOS'), nam.set_index('ICULOS'), nae.set_index('ICULOS')], 
                   axis='columns', keys=[ "with_nan", "na_ma", "na_ma_exponential"])

In [37]:
nan_na_ma_na_exponential

          with_nan                  na_ma            na_ma_exponential        \
       SepsisLabel qSOFA SOFA SepsisLabel qSOFA SOFA       SepsisLabel qSOFA
ICULOS
1                0     0    0           0     1    1                 0     0
2                0     0    0           0     0    0                 0     0
3                0     0    0           0     0    0                 0     0
4                0     1    1           0     1    1                 0     1
5                0     1    0           0     1    1                 0     1
6                0     1    0           0     1    1                 0     1
7                0     1    1           0     1    1                 0     1
8                0     1    0           0     1    1                 0     1
9                0     0    0           0     0    0                 0     0
10               0     1    0           0     1    1                 0     1
11               0     1    0           0     1    1                 0     1
12               0     0    0           0     0    0                 0     1
13               0     1    0           0     1    1                 0     1
14               0     0    0           0     0    0                 0     0
15               0     0    0           0     0    0                 0     0
16               0     0    0           0     0    0                 0     0
17               0     0    0           0     0    0                 0     0
18               0     0    0           0     0    0                 0     0
19               0     0    0           0     0    0                 0     0
20               0     0    0           0     0    0                 0     0
21               0     0    0           0     0    0                 0     0
22               0     1    0           0     1    1                 0     1
23               0     1    0           0     1    1                 0     1
24               0     1    0           0     1    1                 0     1
25               0     1    0           0     1    1                 0     1
26               0     1    1           0     1    1                 0     1
27               0     1    0           0     1    1                 0     1
28               0     1    0           0     1    1                 0     1
29               0     1    0           0     1    1                 0     1
30               0     1    0           0     1    1                 0     1
31               0     1    0           0     1    1                 0     1
32               0     1    1           0     1    1                 0     1
33               0     1    0           0     1    1                 0     1
34               0     1    0           0     1    1                 0     1
35               0     1    0           0     1    1                 0     1
36               0     1    1           0     1    1                 0     1
37               0     1    1           0     1    1                 0     1
38               0     0    0           0     0    0                 0     0
39               0     1    0           0     1    1                 0     1
40               1     1    1           1     1    1                 1     1
41               1     1    0           1     1    1                 1     1
42               1     1    0           1     1    1                 1     1
43               1     1    0           1     1    1                 1     1
44               1     1    0           1     1    1                 1     1
45               1     0    0           1     0    0                 1     0
46               1     0    0           1     0    0                 1     0
47               1     0    0           1     0    0                 1     0
48               1     0    0           1     0    0                 1     0
49               1     0    0           1     0    0                 1     0


       SOFA
ICULOS
1         0
2         0
3         0
4         1
5         1
6         1
7         1
8         1
9         0
10        1
11        1
12        1
13        1
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
30        1
31        1
32        1
33        1
34        1
35        1
36        1
37        1
38        0
39        1
40        1
41        1
42        1
43        1
44        1
45        0
46        0
47        0
48        0
49        0

# na_mean Perform imputation with the overall mean

In [39]:
na_mean=pd.read_table("p015036_sepsis_na_mean.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_mean["Resp"], na_mean["SBP"], na_mean["Platelets"], na_mean["Bilirubin_total"], na_mean["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_mean['qSOFA']=result_qsofa
na_mean['SOFA']=result_sofa

na_mean

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,23.026596,107.648148,138.7,3.911111,3.908333,1,0,1,1
2,20.000000,107.648148,138.7,3.911111,3.908333,2,0,0,0
3,19.000000,107.648148,138.7,3.911111,3.908333,3,0,0,0
4,24.000000,107.648148,138.7,2.300000,3.400000,4,0,1,1
5,25.000000,107.648148,138.7,3.911111,3.908333,5,0,1,1
6,26.000000,107.648148,138.7,3.911111,3.908333,6,0,1,1
7,28.500000,107.648148,187.0,2.700000,3.700000,7,0,1,1
8,24.250000,107.648148,138.7,3.911111,3.908333,8,0,1,1
9,15.000000,107.648148,138.7,3.911111,3.908333,9,0,0,0
10,25.000000,107.648148,138.7,3.911111,3.908333,10,0,1,1
11,26.000000,107.648148,138.7,3.911111,3.908333,11,0,1,1
12,23.026596,107.648148,158.0,3.000000,3.800000,12,0,1,1
13,25.500000,107.648148,138.7,3.911111,3.908333,13,0,1,1
14,19.000000,107.648148,138.7,3.911111,3.908333,14,0,0,0
15,20.000000,107.648148,138.7,3.911111,3.908333,15,0,0,0
16,20.500000,107.648148,138.7,3.911111,3.908333,16,0,0,0
17,20.500000,107.648148,138.7,3.911111,3.908333,17,0,0,0
18,21.500000,107.648148,159.0,3.911111,4.300000,18,0,0,0
19,21.000000,107.648148,138.7,3.911111,3.908333,19,0,0,0
20,18.000000,107.648148,138.7,3.911111,3.908333,20,0,0,0
21,18.750000,107.648148,150.0,3.900000,4.500000,21,0,0,0
22,24.000000,107.648148,138.7,3.911111,3.908333,22,0,1,1
23,29.000000,101.000000,138.7,3.911111,3.908333,23,0,1,1
24,28.000000,106.000000,138.7,3.911111,3.908333,24,0,1,1
25,32.000000,115.500000,138.7,3.911111,3.908333,25,0,1,1
26,23.000000,106.000000,119.0,3.200000,4.400000,26,0,1,1
27,30.000000,118.000000,138.7,3.911111,3.908333,27,0,1,1
28,25.000000,121.000000,138.7,3.911111,3.908333,28,0,1,1
29,25.000000,121.500000,138.7,3.911111,3.908333,29,0,1,1
30,26.000000,121.000000,138.7,3.911111,3.908333,30,0,1,1
31,25.000000,118.000000,138.7,3.911111,3.908333,31,0,1,1
32,30.000000,121.000000,126.0,4.300000,4.600000,32,0,1,1
33,25.000000,117.000000,138.7,3.911111,3.908333,33,0,1,1
34,22.750000,110.000000,138.7,3.911111,3.908333,34,0,1,1
35,23.000000,107.000000,138.7,3.911111,3.908333,35,0,1,1
36,24.000000,110.500000,124.0,4.900000,4.700000,36,0,1,1
37,24.000000,97.000000,138.7,3.911111,4.300000,37,0,1,1
38,21.000000,101.000000,138.7,3.911111,3.908333,38,0,0,0
39,24.000000,107.500000,138.7,3.911111,3.908333,39,0,1,1
40,24.000000,81.500000,106.0,5.200000,3.600000,40,1,1,1
41,20.000000,90.000000,138.7,3.911111,3.908333,41,1,1,1
42,20.000000,96.000000,138.7,3.911111,3.908333,42,1,1,1
43,20.000000,93.000000,138.7,3.911111,3.908333,43,1,1,1
44,20.000000,97.500000,138.7,3.911111,3.908333,44,1,1,1
45,20.000000,110.000000,133.0,5.700000,3.000000,45,1,0,0
46,20.000000,100.500000,138.7,3.911111,3.908333,46,1,0,0
47,20.000000,104.500000,138.7,3.911111,3.908333,47,1,0,0
48,20.000000,129.000000,138.7,3.911111,3.908333,48,1,0,0
49,20.000000,105.500000,125.0,3.911111,2.600000,49,1,0,0

# na_random Missing Value Imputation by Random Sample

In [40]:
na_random=pd.read_table("p015036_sepsis_na_random.psv",sep="|")

# Running sofa and qsofa 
result_qsofa = []
result_sofa= []
        
for a,b,c,d,e in zip(na_random["Resp"], na_random["SBP"], na_random["Platelets"], na_random["Bilirubin_total"], na_random["Creatinine"]): 
    if a>=22 or b<=100: 
        result_qsofa.append(1)
        if c<100 or d>=2 or e>=2: 
            result_sofa.append(1)
        else:
            result_sofa.append(0)
    else:
        result_qsofa.append(0) 
        result_sofa.append(0)
        
na_random['qSOFA']=result_qsofa
na_random['SOFA']=result_sofa

na_random

,Resp,SBP,Platelets,Bilirubin_total,Creatinine,ICULOS,SepsisLabel,qSOFA,SOFA
1,28.371035,121.403479,110.903208,4.107112,3.723817,1,0,1,1
2,20.000000,98.828407,151.855056,4.179021,3.004553,2,0,1,1
3,19.000000,97.853601,113.093970,4.269162,3.417516,3,0,1,1
4,24.000000,91.313668,156.711183,2.300000,3.400000,4,0,1,1
5,25.000000,118.323130,136.014161,3.527136,4.127479,5,0,1,1
6,26.000000,99.855308,167.496524,2.612007,3.155873,6,0,1,1
7,28.500000,127.551262,187.000000,2.700000,3.700000,7,0,1,1
8,24.250000,84.650555,158.094720,3.562116,4.174730,8,0,1,1
9,15.000000,86.699481,171.606264,3.861876,2.903567,9,0,1,1
10,25.000000,106.503506,154.300278,5.697534,4.235846,10,0,1,1
11,26.000000,87.753404,169.806844,3.175102,4.522513,11,0,1,1
12,22.964853,118.017849,158.000000,3.000000,3.800000,12,0,1,1
13,25.500000,102.618793,154.133513,4.148457,3.733470,13,0,1,1
14,19.000000,124.331630,127.461601,4.989310,3.582169,14,0,0,0
15,20.000000,106.184930,164.504530,2.793756,2.989425,15,0,0,0
16,20.500000,119.094112,163.109665,3.340221,4.355927,16,0,0,0
17,20.500000,93.209299,131.755045,4.743882,4.135457,17,0,1,1
18,21.500000,119.004777,159.000000,4.097381,4.300000,18,0,0,0
19,21.000000,99.994694,173.758831,4.985590,4.684430,19,0,1,1
20,18.000000,84.758559,119.793723,3.185865,3.192716,20,0,1,1
21,18.750000,126.361697,150.000000,3.900000,4.500000,21,0,0,0
22,24.000000,112.253629,156.771486,3.876323,4.108076,22,0,1,1
23,29.000000,101.000000,172.413109,4.636013,3.706731,23,0,1,1
24,28.000000,106.000000,149.358183,4.543971,3.479527,24,0,1,1
25,32.000000,115.500000,148.989451,3.137258,3.937504,25,0,1,1
26,23.000000,106.000000,119.000000,3.200000,4.400000,26,0,1,1
27,30.000000,118.000000,134.433975,2.921764,4.679640,27,0,1,1
28,25.000000,121.000000,115.367224,4.678740,2.711057,28,0,1,1
29,25.000000,121.500000,142.603886,5.358104,4.405986,29,0,1,1
30,26.000000,121.000000,142.457575,3.847644,3.646558,30,0,1,1
31,25.000000,118.000000,163.371144,3.217624,4.091358,31,0,1,1
32,30.000000,121.000000,126.000000,4.300000,4.600000,32,0,1,1
33,25.000000,117.000000,111.158296,4.436697,4.235915,33,0,1,1
34,22.750000,110.000000,112.943053,4.769069,2.715692,34,0,1,1
35,23.000000,107.000000,151.367590,3.044328,3.289069,35,0,1,1
36,24.000000,110.500000,124.000000,4.900000,4.700000,36,0,1,1
37,24.000000,97.000000,156.593604,5.196013,4.300000,37,0,1,1
38,21.000000,101.000000,158.183119,4.001991,3.386912,38,0,0,0
39,24.000000,107.500000,110.920974,4.456491,2.689373,39,0,1,1
40,24.000000,81.500000,106.000000,5.200000,3.600000,40,1,1,1
41,20.000000,90.000000,107.111522,4.868902,3.598629,41,1,1,1
42,20.000000,96.000000,148.053345,3.806949,4.512127,42,1,1,1
43,20.000000,93.000000,184.529674,5.648338,2.808626,43,1,1,1
44,20.000000,97.500000,133.493406,2.760528,4.617206,44,1,1,1
45,20.000000,110.000000,133.000000,5.700000,3.000000,45,1,0,0
46,20.000000,100.500000,142.490968,3.171323,4.197172,46,1,0,0
47,20.000000,104.500000,162.814083,2.666237,4.622315,47,1,0,0
48,20.000000,129.000000,109.642125,3.178054,2.909446,48,1,0,0
49,20.000000,105.500000,125.000000,4.468080,2.600000,49,1,0,0

In [41]:
i=nandf[['SepsisLabel','ICULOS','qSOFA','SOFA']]
namean=na_mean[['SepsisLabel','ICULOS','qSOFA','SOFA']]
narandom=na_random[['SepsisLabel','ICULOS','qSOFA','SOFA']]
nan_na_mean_na_random = pd.concat([i.set_index('ICULOS'), namean.set_index('ICULOS'), narandom.set_index('ICULOS')], 
                   axis='columns', keys=[ "with_nan", "na_mean", "na_random"])

In [42]:
nan_na_mean_na_random

          with_nan                na_mean              na_random
       SepsisLabel qSOFA SOFA SepsisLabel qSOFA SOFA SepsisLabel qSOFA SOFA
ICULOS
1                0     0    0           0     1    1           0     1    1
2                0     0    0           0     0    0           0     1    1
3                0     0    0           0     0    0           0     1    1
4                0     1    1           0     1    1           0     1    1
5                0     1    0           0     1    1           0     1    1
6                0     1    0           0     1    1           0     1    1
7                0     1    1           0     1    1           0     1    1
8                0     1    0           0     1    1           0     1    1
9                0     0    0           0     0    0           0     1    1
10               0     1    0           0     1    1           0     1    1
11               0     1    0           0     1    1           0     1    1
12               0     0    0           0     1    1           0     1    1
13               0     1    0           0     1    1           0     1    1
14               0     0    0           0     0    0           0     0    0
15               0     0    0           0     0    0           0     0    0
16               0     0    0           0     0    0           0     0    0
17               0     0    0           0     0    0           0     1    1
18               0     0    0           0     0    0           0     0    0
19               0     0    0           0     0    0           0     1    1
20               0     0    0           0     0    0           0     1    1
21               0     0    0           0     0    0           0     0    0
22               0     1    0           0     1    1           0     1    1
23               0     1    0           0     1    1           0     1    1
24               0     1    0           0     1    1           0     1    1
25               0     1    0           0     1    1           0     1    1
26               0     1    1           0     1    1           0     1    1
27               0     1    0           0     1    1           0     1    1
28               0     1    0           0     1    1           0     1    1
29               0     1    0           0     1    1           0     1    1
30               0     1    0           0     1    1           0     1    1
31               0     1    0           0     1    1           0     1    1
32               0     1    1           0     1    1           0     1    1
33               0     1    0           0     1    1           0     1    1
34               0     1    0           0     1    1           0     1    1
35               0     1    0           0     1    1           0     1    1
36               0     1    1           0     1    1           0     1    1
37               0     1    1           0     1    1           0     1    1
38               0     0    0           0     0    0           0     0    0
39               0     1    0           0     1    1           0     1    1
40               1     1    1           1     1    1           1     1    1
41               1     1    0           1     1    1           1     1    1
42               1     1    0           1     1    1           1     1    1
43               1     1    0           1     1    1           1     1    1
44               1     1    0           1     1    1           1     1    1
45               1     0    0           1     0    0           1     0    0
46               1     0    0           1     0    0           1     0    0
47               1     0    0           1     0    0           1     0    0
48               1     0    0           1     0    0           1     0    0
49               1     0    0           1     0    0           1     0    0