In [1]:
import os
import pandas as pd
directory='/home/ibab/Pictures/working_on_small_subset_for_sofa_qsofa_scoring'

for filename in os.listdir(directory):
    if filename.endswith(".psv"):
        data=pd.read_table(filename, sep='|', engine='python')
        result_qsofa = []
        result_sofa= []
        
        for a,b,c,d,e in zip(data["Resp"], data["SBP"],data["Platelets"],data["Bilirubin_total"],data["Creatinine"]): 
            if a>=22 or b<=100: 
                result_qsofa.append(1)
                if c<100 or d>=2 or e>=2: 
                    result_sofa.append(1)
                else:
                    result_sofa.append(0)
            else:
                result_qsofa.append(0)
                result_sofa.append(0)
        
        data['qSOFA']=result_qsofa
        data['SOFA']=result_sofa
        print(data)
        data.to_csv(filename,sep='|')

       HR  O2Sat   Temp    SBP    MAP    DBP  Resp  EtCO2  BaseExcess  HCO3  \
0     NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN         NaN   NaN
1    93.0   95.0  39.50  120.5   91.0   72.0  26.0    NaN         NaN   NaN
2    84.0   96.0    NaN  147.0  119.0  100.0  22.0    NaN         NaN   NaN
3    74.0   97.0  38.28  140.0  111.0   92.0  22.0    NaN         NaN   NaN
4    74.0   99.0    NaN  144.0  116.0   98.0  19.0    NaN         NaN  24.0
5    75.0   98.0  38.39  157.0  134.0  117.0  21.0    NaN         NaN  24.0
6    70.0   96.0    NaN  110.0   69.0   60.0  25.0    NaN         NaN   NaN
7    85.0   99.0  37.94  107.0   81.0   65.0  19.0    NaN         NaN   NaN
8    79.0   98.0    NaN  100.0   70.0   56.0  23.0    NaN         NaN   NaN
9     NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN         NaN   NaN
10   99.0  100.0  37.17   91.0   70.0   57.0  20.0    NaN         NaN   NaN
11  102.0  100.0    NaN  152.0  123.0  108.0  24.0    NaN         NaN   NaN
12  101.0  100.0    NaN   93.0   67.0   51.0  24.0    NaN         NaN   NaN
13   98.0  100.0    NaN  140.0  113.0   97.0  18.0    NaN         NaN   NaN
14  100.0  100.0  38.17   98.0   70.0   53.0  20.0    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  22.61       0      1      0        -7.05       1
1   ...        NaN  22.61       0      1      0        -7.05       2
2   ...        NaN  22.61       0      1      0        -7.05       3
3   ...        NaN  22.61       0      1      0        -7.05       4
4   ...      111.0  22.61       0      1      0        -7.05       5
5   ...        NaN  22.61       0      1      0        -7.05       6
6   ...        NaN  22.61       0      1      0        -7.05       7
7   ...        NaN  22.61       0      1      0        -7.05       8
8   ...        NaN  22.61       0      1      0        -7.05       9
9   ...        NaN  22.61       0      1      0        -7.05      10
10  ...       90.0  22.61       0      1      0        -7.05      11
11  ...        NaN  22.61       0      1      0        -7.05      12
12  ...        NaN  22.61       0      1      0        -7.05      13
13  ...        NaN  22.61       0      1      0        -7.05      14
14  ...      103.0  22.61       0      1      0        -7.05      15

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      1     0
2             0      1     0
3             0      1     0
4             0      0     0
5             1      0     0
6             1      1     0
7             1      0     0
8             1      1     0
9             1      0     0
10            1      1     1
11            1      1     0
12            1      1     0
13            1      0     0
14            1      1     0

[15 rows x 43 columns]
      HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  ...  \
0    NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN         NaN   NaN  ...
1   47.0   93.0    NaN  101.0  77.0  60.0  21.0    NaN         NaN   NaN  ...
2    NaN   95.0    NaN    NaN   NaN   NaN  28.0    NaN         0.0   NaN  ...
3   48.0   97.0  35.94  110.0  83.0  64.0  25.0    NaN         NaN   NaN  ...
4   51.0   96.0    NaN  102.0  75.0  56.0  28.0    NaN         NaN   NaN  ...
..   ...    ...    ...    ...   ...   ...   ...    ...         ...   ...  ...
93  44.0   96.5    NaN  119.5  85.5  65.5  28.0    NaN         6.0   NaN  ...
94  42.0   95.0    NaN  120.0  85.0  64.0  28.0    NaN         NaN   NaN  ...
95  56.0   94.0  36.28  109.0  74.0  55.0  28.0    NaN         NaN   NaN  ...
96  67.0   91.5    NaN  120.0  90.0  65.5  28.0    NaN         NaN   NaN  ...
97  45.0   96.0    NaN  109.0  79.0  61.0  28.0    NaN         NaN   NaN  ...

    Platelets   Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  SepsisLabel  \
0         NaN  64.5       0      1      0        -0.05       1            0
1         NaN  64.5       0      1      0        -0.05       2            0
2         NaN  64.5       0      1      0        -0.05       3            0
3         NaN  64.5       0      1      0        -0.05       4            0
4         NaN  64.5       0      1      0        -0.05       5            0
..        ...   ...     ...    ...    ...          ...     ...          ...
93        NaN  64.5       0      1      0        -0.05      94            1
94        NaN  64.5       0      1      0        -0.05      95            1
95        NaN  64.5       0      1      0        -0.05      96            1
96        NaN  64.5       0      1      0        -0.05      97            1
97        NaN  64.5       0      1      0        -0.05      98            1

    qSOFA  SOFA
0       0     0
1       0     0
2       1     0
3       1     0
4       1     0
..    ...   ...
93      1     0
94      1     0
95      1     0
96      1     0
97      1     0

[98 rows x 43 columns]
       HR  O2Sat   Temp    SBP    MAP    DBP  Resp  EtCO2  BaseExcess  HCO3  \
0     NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN         NaN   NaN
1   100.0   97.5  38.44  102.0   72.0   58.0  14.0    NaN         NaN   NaN
2    89.0   98.0    NaN   97.0   71.0   58.0  22.0    NaN         NaN   NaN
3    86.0   98.0    NaN   99.0   72.0   57.0  26.0    NaN         NaN   NaN
4    97.0   98.0  37.44  112.0   76.0   59.0  31.5    NaN        -6.0   NaN
5   124.0   91.0    NaN  141.0   90.0   69.0  33.0    NaN         NaN   NaN
6   112.0   94.0    NaN  108.0   78.0   63.0  30.0    NaN         NaN   NaN
7   105.0   94.0    NaN  110.0   79.0   64.0  31.5    NaN         NaN   NaN
8   101.0   96.0  38.11  105.0   77.0   63.0   NaN    NaN        -6.0   NaN
9   106.0   96.0    NaN  124.0   85.0   67.0  33.0    NaN         NaN   NaN
10  111.0   96.0    NaN  124.0   84.0   67.0   NaN    NaN        -8.0   NaN
11  100.0   98.0    NaN  106.0   78.0   65.0  30.0    NaN        -5.0   NaN
12  100.0   96.0  37.39  118.0   97.0   86.0  31.5    NaN        -6.0   NaN
13  104.0   99.0    NaN  129.0   82.0   65.0   NaN    NaN         NaN   NaN
14  105.0   99.0    NaN  141.0   87.0   67.0  30.0    NaN        -4.0   NaN
15  100.0  100.0    NaN  122.0   79.0   63.0   NaN    NaN         NaN   NaN
16  102.0   98.0  38.22  125.0  111.0  104.0  30.5    NaN        -4.0  22.0
17  103.0   98.0    NaN  116.0   98.0   91.0  30.0    NaN         NaN   NaN
18   95.0   98.0    NaN   84.0   63.0   53.0  26.0    NaN         0.0   NaN
19    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN         NaN   NaN
20   95.0   99.0  37.83  118.0  114.0  112.0  26.0    NaN        -2.0   NaN
21   97.0   96.0  38.78   98.0   72.0   59.0  26.0    NaN         NaN   NaN
22   86.0   98.0    NaN   89.0   67.0   56.0  26.0    NaN         NaN   NaN
23   86.0   98.0    NaN   97.0   71.0   58.0   NaN    NaN         NaN   NaN
24   93.0   95.0  39.06   82.0   68.0   61.0  26.0    NaN         NaN  19.0
25   92.0   95.0    NaN   96.0   65.0   52.0  24.0    NaN        -1.0   NaN
26   94.0   96.0    NaN  101.0   68.0   54.0  24.0    NaN         NaN   NaN
27   93.0   95.0    NaN  100.0   67.0   53.0  24.0    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  64.25       1      1      0        -0.03       1
1   ...        NaN  64.25       1      1      0        -0.03       2
2   ...        NaN  64.25       1      1      0        -0.03       3
3   ...        NaN  64.25       1      1      0        -0.03       4
4   ...        NaN  64.25       1      1      0        -0.03       5
5   ...        NaN  64.25       1      1      0        -0.03       6
6   ...        NaN  64.25       1      1      0        -0.03       7
7   ...        NaN  64.25       1      1      0        -0.03       8
8   ...        NaN  64.25       1      1      0        -0.03       9
9   ...        NaN  64.25       1      1      0        -0.03      10
10  ...        NaN  64.25       1      1      0        -0.03      11
11  ...        NaN  64.25       1      1      0        -0.03      12
12  ...        NaN  64.25       1      1      0        -0.03      13
13  ...        NaN  64.25       1      1      0        -0.03      14
14  ...        NaN  64.25       1      1      0        -0.03      15
15  ...        NaN  64.25       1      1      0        -0.03      16
16  ...      183.0  64.25       1      1      0        -0.03      17
17  ...        NaN  64.25       1      1      0        -0.03      18
18  ...        NaN  64.25       1      1      0        -0.03      19
19  ...        NaN  64.25       1      1      0        -0.03      20
20  ...        NaN  64.25       1      1      0        -0.03      21
21  ...        NaN  64.25       1      1      0        -0.03      22
22  ...        NaN  64.25       1      1      0        -0.03      23
23  ...        NaN  64.25       1      1      0        -0.03      24
24  ...        NaN  64.25       1      1      0        -0.03      25
25  ...        NaN  64.25       1      1      0        -0.03      26
26  ...        NaN  64.25       1      1      0        -0.03      27
27  ...        NaN  64.25       1      1      0        -0.03      28

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      0     0
2             0      1     0
3             0      1     0
4             0      1     0
5             0      1     0
6             0      1     0
7             0      1     0
8             0      0     0
9             0      1     0
10            0      0     0
11            0      1     0
12            0      1     0
13            0      0     0
14            0      1     0
15            0      0     0
16            0      1     1
17            0      1     0
18            1      1     0
19            1      0     0
20            1      1     0
21            1      1     0
22            1      1     0
23            1      1     0
24            1      1     1
25            1      1     0
26            1      1     0
27            1      1     0

[28 rows x 43 columns]
       HR  O2Sat   Temp     SBP   MAP    DBP  Resp  EtCO2  BaseExcess  HCO3  \
0    75.0  100.0  34.25  104.00  64.0   46.0  10.0    NaN        -1.0  23.0
1    77.5   99.5  34.70  114.50  70.0   48.0  14.0    NaN        -3.0   NaN
2    77.0  100.0  35.65  102.50  61.5   42.5  11.5    NaN         NaN   NaN
3    78.0   99.0  36.95  108.00  64.5   45.0  16.5    NaN         NaN   NaN
4    89.0   98.0  37.20  104.00  60.0   40.5  21.5    NaN         NaN   NaN
5    79.5   97.0  37.15  105.00  58.5   38.5  23.0    NaN        -2.0   NaN
6    78.0   96.0  37.20  108.00  60.0   40.0  24.0    NaN        -2.0   NaN
7    75.0   96.0  37.40  102.00  57.0   38.0  23.0    NaN         NaN   NaN
8    73.0   97.0  37.50  115.00  64.0   42.0  23.0    NaN         NaN   NaN
9    72.0   96.0  37.60  120.00  65.0   43.0  22.0    NaN         NaN   NaN
10   74.0   94.0  37.60  115.00  64.0   42.0  20.0    NaN         NaN   NaN
11   76.0   94.0  37.70  124.00  67.0   44.0  25.0    NaN         NaN   NaN
12   74.0   94.0  37.80  126.00  67.0   43.0  24.0    NaN         NaN   NaN
13   76.0   92.5  37.90  114.00  63.0   42.0  23.5    NaN         NaN  22.0
14   78.5   95.0  38.00  107.00  64.0   44.0  22.5    NaN         0.0   NaN
15   76.0   95.0  38.10  107.00  63.0   42.0  25.0    NaN         NaN   NaN
16   82.0   94.0  38.10  103.00  71.0   52.0  30.0    NaN        -2.0   NaN
17   75.0   96.0  38.20  119.00  67.0   45.0  20.0    NaN        -1.0   NaN
18   74.0   94.0  38.20  112.00  61.0   40.0  19.0    NaN         NaN   NaN
19   75.0   94.0  38.30  110.00  61.0   41.0  20.0    NaN         NaN   NaN
20   75.0   94.0  38.40  110.00  63.0   42.0  22.0    NaN         NaN   NaN
21   76.0   92.0  38.40  125.00  68.0   46.0  22.0    NaN         NaN   NaN
22   80.0   96.0  38.50  112.00  66.0   46.0  22.0    NaN         NaN   NaN
23   76.0   91.0  38.50  105.00  55.0   52.0  26.0    NaN         NaN   NaN
24   76.0   92.0    NaN   97.00  62.0   43.0  25.0    NaN         NaN   NaN
25   78.0   93.0  38.11  109.00  57.0   43.0  24.0    NaN        -1.0   NaN
26   83.0   93.0    NaN  152.50  55.0  116.0  29.0    NaN         NaN   NaN
27   81.0   99.0    NaN  104.00  61.0    NaN  29.0    NaN         NaN   NaN
28   81.0   96.0  36.89  110.00  55.0   32.0  26.0    NaN         NaN   NaN
29   79.0   94.0    NaN  110.00  52.0   36.0  21.0    NaN         NaN   NaN
30   76.0   93.0    NaN  104.00  53.0   34.0  23.0    NaN         NaN   NaN
31   81.0   95.0    NaN  117.00  60.0   37.0  28.0    NaN         NaN   NaN
32   76.0   95.0  36.11  120.00  57.0   36.0  29.0    NaN         NaN   NaN
33   79.0   97.0    NaN  105.50  55.0   34.0  29.0    NaN         NaN   NaN
34   79.0   95.0    NaN  120.50  54.0   40.0  28.0    NaN         NaN   NaN
35   82.0   95.0    NaN  121.00  61.0   37.0  28.0    NaN         NaN   NaN
36   82.0   96.0  37.28  112.00  57.0   36.0  28.0    NaN         NaN   NaN
37   82.0   98.0    NaN  107.00  56.0   35.0  27.0    NaN         NaN   NaN
38   72.0   97.0    NaN   88.00  47.0   30.0  25.0    NaN         NaN   NaN
39   81.0   96.0    NaN  122.00  69.0   42.0  26.0    NaN         NaN  25.0
40   74.0   96.0  37.22  110.00  59.0   36.0  26.0    NaN         0.0   NaN
41   81.0   96.0    NaN  116.00  63.0   39.0  28.0    NaN         NaN   NaN
42   78.0   95.0    NaN  118.00  56.0   32.0  19.0    NaN        -3.0   NaN
43   81.0   91.0    NaN  123.00  60.0   35.0  24.0    NaN         NaN   NaN
44   83.0   96.0  37.33  135.00  70.0   41.0  27.0    NaN         NaN   NaN
45   93.0   92.0    NaN  122.00  66.0   39.0  29.0    NaN         NaN   NaN
46   89.0   95.0  38.39  119.00  61.0   35.0  24.0    NaN         NaN   NaN
47    NaN   98.0    NaN  105.00  58.0   37.0  26.0    NaN         NaN   NaN
48   87.0   92.0    NaN  111.00  64.0   41.0  29.0    NaN         NaN   NaN
49   87.0   98.0  37.94  116.00  61.0   38.0  25.0    NaN         NaN   NaN
50   91.0   96.0    NaN  121.00  64.0   40.0  22.0    NaN         NaN   NaN
51   91.0   93.0    NaN  119.00  60.0   35.0  31.0    NaN         NaN   NaN
52   87.0   95.0  37.83  129.00  62.0   44.0  31.0    NaN         NaN   NaN
53   89.0   96.0    NaN  117.00  63.0   40.0  34.0    NaN         NaN   NaN
54   98.0   94.0  39.00  114.00  66.0   43.0  35.0    NaN         NaN   NaN
55  103.0   95.0    NaN  100.00  61.0   41.0  34.0    NaN         NaN   NaN
56   91.5   96.0  38.61   97.25  54.0   48.0  31.0    NaN         0.0   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...      104.0  85.71       0      0      1        -3.21       2
1   ...        NaN  85.71       0      0      1        -3.21       3
2   ...        NaN  85.71       0      0      1        -3.21       4
3   ...        NaN  85.71       0      0      1        -3.21       5
4   ...        NaN  85.71       0      0      1        -3.21       6
5   ...        NaN  85.71       0      0      1        -3.21       7
6   ...        NaN  85.71       0      0      1        -3.21       8
7   ...        NaN  85.71       0      0      1        -3.21       9
8   ...        NaN  85.71       0      0      1        -3.21      10
9   ...        NaN  85.71       0      0      1        -3.21      11
10  ...        NaN  85.71       0      0      1        -3.21      12
11  ...        NaN  85.71       0      0      1        -3.21      13
12  ...        NaN  85.71       0      0      1        -3.21      14
13  ...      139.0  85.71       0      0      1        -3.21      15
14  ...        NaN  85.71       0      0      1        -3.21      16
15  ...        NaN  85.71       0      0      1        -3.21      17
16  ...        NaN  85.71       0      0      1        -3.21      18
17  ...        NaN  85.71       0      0      1        -3.21      19
18  ...        NaN  85.71       0      0      1        -3.21      20
19  ...        NaN  85.71       0      0      1        -3.21      21
20  ...        NaN  85.71       0      0      1        -3.21      22
21  ...        NaN  85.71       0      0      1        -3.21      23
22  ...        NaN  85.71       0      0      1        -3.21      24
23  ...        NaN  85.71       0      0      1        -3.21      25
24  ...        NaN  85.71       0      0      1        -3.21      26
25  ...        NaN  85.71       0      0      1        -3.21      27
26  ...        NaN  85.71       0      0      1        -3.21      28
27  ...        NaN  85.71       0      0      1        -3.21      29
28  ...        NaN  85.71       0      0      1        -3.21      30
29  ...        NaN  85.71       0      0      1        -3.21      31
30  ...        NaN  85.71       0      0      1        -3.21      32
31  ...        NaN  85.71       0      0      1        -3.21      33
32  ...        NaN  85.71       0      0      1        -3.21      34
33  ...        NaN  85.71       0      0      1        -3.21      35
34  ...        NaN  85.71       0      0      1        -3.21      36
35  ...        NaN  85.71       0      0      1        -3.21      37
36  ...        NaN  85.71       0      0      1        -3.21      38
37  ...        NaN  85.71       0      0      1        -3.21      39
38  ...        NaN  85.71       0      0      1        -3.21      40
39  ...      106.0  85.71       0      0      1        -3.21      41
40  ...        NaN  85.71       0      0      1        -3.21      42
41  ...        NaN  85.71       0      0      1        -3.21      43
42  ...        NaN  85.71       0      0      1        -3.21      44
43  ...        NaN  85.71       0      0      1        -3.21      45
44  ...        NaN  85.71       0      0      1        -3.21      46
45  ...        NaN  85.71       0      0      1        -3.21      47
46  ...        NaN  85.71       0      0      1        -3.21      48
47  ...        NaN  85.71       0      0      1        -3.21      49
48  ...        NaN  85.71       0      0      1        -3.21      50
49  ...        NaN  85.71       0      0      1        -3.21      51
50  ...        NaN  85.71       0      0      1        -3.21      52
51  ...        NaN  85.71       0      0      1        -3.21      53
52  ...        NaN  85.71       0      0      1        -3.21      54
53  ...        NaN  85.71       0      0      1        -3.21      55
54  ...        NaN  85.71       0      0      1        -3.21      56
55  ...        NaN  85.71       0      0      1        -3.21      57
56  ...        NaN  85.71       0      0      1        -3.21      58

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      0     0
2             0      0     0
3             0      0     0
4             0      0     0
5             0      1     0
6             0      1     0
7             0      1     0
8             0      1     0
9             0      1     0
10            0      0     0
11            0      1     0
12            0      1     0
13            0      1     0
14            0      1     0
15            0      1     0
16            0      1     0
17            0      0     0
18            0      0     0
19            0      0     0
20            0      1     0
21            0      1     0
22            0      1     0
23            0      1     0
24            0      1     0
25            0      1     0
26            0      1     0
27            0      1     0
28            0      1     0
29            0      0     0
30            0      1     0
31            0      1     0
32            0      1     0
33            0      1     0
34            0      1     0
35            0      1     0
36            0      1     0
37            0      1     0
38            0      1     0
39            0      1     0
40            0      1     0
41            0      1     0
42            0      0     0
43            0      1     0
44            0      1     0
45            0      1     0
46            0      1     0
47            1      1     0
48            1      1     0
49            1      1     0
50            1      1     0
51            1      1     0
52            1      1     0
53            1      1     0

      HR  O2Sat   Temp  SBP    MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  ...  \
0    NaN    NaN    NaN  NaN    NaN  NaN   NaN    NaN         NaN   NaN  ...
1   71.0   99.5    NaN  NaN   88.0  NaN  18.0    NaN         NaN  31.0  ...
2   77.0  100.0    NaN  NaN   92.0  NaN  18.0    NaN         NaN   NaN  ...
3   79.0   99.0  36.44  NaN   99.0  NaN  16.0    NaN         4.0   NaN  ...
4   79.0  100.0    NaN  NaN   99.0  NaN  14.0    NaN         4.0   NaN  ...
..   ...    ...    ...  ...    ...  ...   ...    ...         ...   ...  ...
78  61.0   94.0    NaN  NaN   82.0  NaN  24.0    NaN         NaN   NaN  ...
79  77.0   95.0  38.11  NaN  120.0  NaN  16.0    NaN         NaN   NaN  ...
80  71.0   98.0    NaN  NaN   83.0  NaN  20.0    NaN         NaN   NaN  ...
81  72.0   92.0  37.56  NaN    NaN  NaN  20.0    NaN         NaN   NaN  ...
82  69.0   96.0    NaN  NaN   82.5  NaN  20.0    NaN         NaN   NaN  ...

    Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  SepsisLabel  \
0         NaN  61.66       0    NaN    NaN        -0.01       1            0
1         NaN  61.66       0    NaN    NaN        -0.01       2            0
2         NaN  61.66       0    NaN    NaN        -0.01       3            0
3         NaN  61.66       0    NaN    NaN        -0.01       4            0
4         NaN  61.66       0    NaN    NaN        -0.01       5            0
..        ...    ...     ...    ...    ...          ...     ...          ...
78        NaN  61.66       0    NaN    NaN        -0.01      79            1
79        NaN  61.66       0    NaN    NaN        -0.01      80            1
80        NaN  61.66       0    NaN    NaN        -0.01      81            1
81        NaN  61.66       0    NaN    NaN        -0.01      82            1
82        NaN  61.66       0    NaN    NaN        -0.01      83            1

    qSOFA  SOFA
0       0     0
1       0     0
2       0     0
3       0     0
4       0     0
..    ...   ...
78      1     0
79      0     0
80      0     0
81      0     0
82      0     0

[83 rows x 43 columns]
       HR  O2Sat   Temp    SBP     MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  \
0     NaN    NaN    NaN    NaN     NaN  NaN   NaN    NaN         NaN   NaN
1    89.0   99.0    NaN  128.0   97.33  NaN  18.0    NaN         NaN   NaN
2    84.0   99.0    NaN  143.0  103.00  NaN  19.0    NaN         NaN   NaN
3    89.5   85.5    NaN  131.0   97.67  NaN  18.5    NaN         NaN   NaN
4   117.5    NaN    NaN  137.0   98.67  NaN  19.5    NaN         NaN   NaN
5   116.5    NaN    NaN  159.0  105.67  NaN  18.0    NaN         NaN   NaN
6   129.0    NaN  37.72  168.0  111.50  NaN  25.0    NaN         NaN   NaN
7   135.5    NaN    NaN  159.5  113.67  NaN  25.5    NaN         NaN   NaN
8   109.5    NaN    NaN  132.5   92.17  NaN  30.5    NaN         NaN   NaN
9    96.0    NaN    NaN  122.0   87.17  NaN  27.0    NaN         NaN   NaN
10  102.0    NaN    NaN  137.0  105.50  NaN  25.5    NaN         NaN   NaN
11  106.0    NaN    NaN  118.0   86.00  NaN  23.0    NaN         NaN   NaN
12  106.5    NaN    NaN  171.0  145.67  NaN  29.0    NaN         NaN  19.0
13  109.0    NaN    NaN  149.5  107.83  NaN  23.5    NaN         NaN   NaN
14   89.5   98.0  36.22  125.0   87.33  NaN  28.0    NaN         NaN   NaN
15   89.5   97.0    NaN  120.5   82.83  NaN  27.5    NaN         NaN   NaN
16   85.0   97.5    NaN  120.5   81.50  NaN  23.0    NaN         NaN   NaN
17  101.0   98.0    NaN  120.5   87.17  NaN  18.5    NaN        -4.0  21.0
18  132.5   96.0    NaN  154.0  108.33  NaN  22.0    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  28.91       1      1      0       -30.91       1
1   ...        NaN  28.91       1      1      0       -30.91       2
2   ...        NaN  28.91       1      1      0       -30.91       3
3   ...        NaN  28.91       1      1      0       -30.91       4
4   ...        NaN  28.91       1      1      0       -30.91       5
5   ...        NaN  28.91       1      1      0       -30.91       6
6   ...        NaN  28.91       1      1      0       -30.91       7
7   ...        NaN  28.91       1      1      0       -30.91       8
8   ...        NaN  28.91       1      1      0       -30.91       9
9   ...        NaN  28.91       1      1      0       -30.91      10
10  ...        NaN  28.91       1      1      0       -30.91      11
11  ...        NaN  28.91       1      1      0       -30.91      12
12  ...        NaN  28.91       1      1      0       -30.91      13
13  ...        NaN  28.91       1      1      0       -30.91      14
14  ...        NaN  28.91       1      1      0       -30.91      15
15  ...        NaN  28.91       1      1      0       -30.91      16
16  ...        NaN  28.91       1      1      0       -30.91      17
17  ...      132.0  28.91       1      1      0       -30.91      18
18  ...        NaN  28.91       1      1      0       -30.91      19

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      0     0
2             0      0     0
3             0      0     0
4             0      0     0
5             0      0     0
6             0      1     0
7             0      1     0
8             0      1     0
9             1      1     0
10            1      1     0
11            1      1     0
12            1      1     0
13            1      1     0
14            1      1     0
15            1      1     0
16            1      1     0
17            1      0     0
18            1      1     0

[19 rows x 43 columns]
       HR  O2Sat   Temp    SBP   MAP   DBP   Resp  EtCO2  BaseExcess  HCO3  \
0    94.0    100  38.67    NaN  57.0   NaN  17.00    NaN        -9.0   NaN
1    88.0     99    NaN  114.0  70.0  51.0  17.00    NaN         NaN   NaN
2    70.0     99    NaN  114.0  69.0  50.0  15.00    NaN        -5.0  17.0
3    67.0     98    NaN  103.5  60.0  45.0  16.00    NaN        -5.0  17.0
4    68.0     99    NaN  105.0  61.0  45.0  16.00    NaN         NaN   NaN
5    75.0    100    NaN  117.0  66.0  48.0  16.00    NaN         NaN   NaN
6    82.0    100  38.11  148.0  82.0  57.0  16.50    NaN         NaN   NaN
7    95.0    100    NaN  166.0  87.0  62.0  19.00    NaN        -8.0  15.0
8   113.0    100    NaN  186.0  96.0  67.0  25.00    NaN        -8.0  15.0
9   106.0    100  38.33  148.5  78.5  55.0  19.00    NaN         NaN   NaN
10  101.0    100  39.83  130.0  69.0  50.0  19.00    NaN         NaN   NaN
11  102.0     99    NaN  108.0  60.0  44.0  17.00    NaN         NaN   NaN
12  101.0    100  39.97  100.0  58.0  45.0  15.00    NaN         NaN   NaN
13  100.0    100  37.94   97.0  56.0  43.0  16.00    NaN        -8.0   NaN
14   90.5     97  38.00   87.0  52.0  41.0  18.75    NaN        -8.0   NaN
15   89.0    100  37.56  101.0  60.0  45.0  17.00    NaN         NaN   NaN
16   88.0    100    NaN   95.0  57.5  43.0  16.00    NaN       -11.0  13.0

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  74.25       1    NaN    NaN        -0.02       2
1   ...        NaN  74.25       1    NaN    NaN        -0.02       3
2   ...        NaN  74.25       1    NaN    NaN        -0.02       4
3   ...        NaN  74.25       1    NaN    NaN        -0.02       5
4   ...        NaN  74.25       1    NaN    NaN        -0.02       6
5   ...        NaN  74.25       1    NaN    NaN        -0.02       7
6   ...        NaN  74.25       1    NaN    NaN        -0.02       8
7   ...      378.0  74.25       1    NaN    NaN        -0.02       9
8   ...        NaN  74.25       1    NaN    NaN        -0.02      10
9   ...        NaN  74.25       1    NaN    NaN        -0.02      11
10  ...        NaN  74.25       1    NaN    NaN        -0.02      12
11  ...        NaN  74.25       1    NaN    NaN        -0.02      13
12  ...        NaN  74.25       1    NaN    NaN        -0.02      14
13  ...        NaN  74.25       1    NaN    NaN        -0.02      15
14  ...        NaN  74.25       1    NaN    NaN        -0.02      16
15  ...        NaN  74.25       1    NaN    NaN        -0.02      17
16  ...      353.0  74.25       1    NaN    NaN        -0.02      18

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      0     0
2             0      0     0
3             0      0     0
4             0      0     0
5             0      0     0
6             0      0     0
7             1      0     0
8             1      1     0
9             1      0     0
10            1      0     0
11            1      0     0
12            1      1     0
13            1      1     0
14            1      1     0
15            1      0     0
16            1      1     1

[17 rows x 43 columns]
      HR  O2Sat   Temp    SBP     MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
0   96.0   98.0  37.06   93.0   67.00   NaN  18.0    NaN         0.0   NaN
1   87.0   99.0    NaN   98.0   70.00   NaN  16.0    NaN         NaN   NaN
2   72.0  100.0  36.22   89.0   66.33   NaN  16.0    NaN         NaN   NaN
3   70.0  100.0    NaN   99.0   71.67   NaN  16.0    NaN         2.0   NaN
4   72.0  100.0    NaN   99.0   76.33   NaN  16.0    NaN         NaN  26.0
5   69.0   98.0    NaN   94.0   75.33   NaN  16.0    NaN         NaN   NaN
6   68.0   98.0  36.00   97.0   77.00   NaN  16.0    NaN         NaN   NaN
7   74.0   97.0    NaN  102.0   81.33   NaN  16.0    NaN         NaN   NaN
8   65.0   98.0    NaN  111.0   56.33   NaN  16.0    NaN         NaN   NaN
9   66.0   98.0    NaN   96.0   72.00   NaN  16.0    NaN         NaN  26.0
10  68.0   98.0  35.17   94.0   74.00   NaN  16.0    NaN         NaN   NaN
11  68.0   99.0  35.28  104.0   77.33   NaN  16.0    NaN         NaN   NaN
12  69.0  100.0  35.50   97.0   83.67   NaN  16.0    NaN         NaN   NaN
13  83.0  100.0    NaN  106.0   82.67   NaN  16.0    NaN         NaN   NaN
14  81.0  100.0  35.89   99.0   79.00   NaN  16.0    NaN         NaN   NaN
15  90.0   99.0    NaN  104.0   81.33   NaN  20.0    NaN         0.0   NaN
16  73.0   99.0    NaN  127.5   96.50   NaN  18.5    NaN         NaN   NaN
17  82.0   99.0    NaN  125.0   96.33   NaN  21.0    NaN         NaN   NaN
18  83.0   93.0  36.72   99.0   72.33   NaN  20.0    NaN         1.0   NaN
19  75.0   95.0    NaN  111.0   82.33   NaN  19.0    NaN         NaN   NaN
20  79.0   97.0    NaN  120.0   90.00   NaN  24.0    NaN         NaN   NaN
21  78.0   97.0    NaN  112.0   80.67   NaN  25.0    NaN         NaN   NaN
22  83.0   97.0  36.61   98.0   70.67   NaN  16.0    NaN         NaN   NaN
23  68.0   98.0    NaN  112.0   82.00   NaN  16.0    NaN         NaN   NaN
24  60.0   97.0    NaN  117.0   88.33   NaN  16.0    NaN         NaN  26.0
25  55.0   97.0    NaN  113.0   86.33   NaN  16.0    NaN         NaN   NaN
26  62.0   98.0  36.22  131.0   99.00   NaN  16.0    NaN         NaN   NaN
27  64.0   98.0    NaN  127.0   93.00   NaN  16.0    NaN         NaN   NaN
28  64.0   98.0    NaN  129.0   97.67   NaN  16.0    NaN         NaN   NaN
29  83.0   98.0    NaN  139.0  102.33   NaN  25.0    NaN         NaN   NaN
30  65.0   98.0  36.28  131.0   99.00   NaN  16.5    NaN         NaN   NaN
31  65.0   99.0    NaN  135.0  105.00   NaN  17.0    NaN         NaN   NaN
32  59.0   99.0    NaN  125.0  101.00   NaN  18.0    NaN         NaN   NaN
33  53.0   99.0    NaN  118.0   92.00   NaN  16.0    NaN         NaN   NaN
34  56.0  100.0  35.00  123.0   93.00   NaN  18.0    NaN         NaN  25.0
35  51.0   98.0    NaN  134.0   90.67   NaN  16.0    NaN         NaN   NaN
36  56.0   98.0    NaN  124.0   90.00   NaN  16.0    NaN         NaN   NaN
37  65.0   97.0    NaN  116.0   83.33   NaN  19.0    NaN         NaN   NaN
38  73.0   97.0  36.33  125.0   88.33   NaN  18.5    NaN         NaN   NaN
39  69.0   97.0    NaN  120.0   85.33   NaN  22.0    NaN         0.0   NaN
40  88.0   96.0    NaN  125.0   83.67   NaN  19.0    NaN         NaN   NaN
41  84.0   96.0  36.78  123.0   91.67   NaN  26.0    NaN         NaN   NaN
42  83.0   96.0    NaN  117.0   82.33   NaN  19.0    NaN         NaN   NaN
43  80.0   97.0    NaN  120.0   83.33   NaN  19.0    NaN         NaN   NaN
44  78.0   98.0    NaN  118.0   80.67   NaN  18.0    NaN         NaN   NaN
45  78.0   98.0    NaN  111.0   81.67   NaN  17.0    NaN         NaN   NaN
46  70.0   99.0  36.78  147.0  100.33   NaN  15.5    NaN         NaN   NaN
47  67.0   99.0    NaN  151.0   98.33   NaN  16.0    NaN         NaN   NaN
48   NaN    NaN    NaN    NaN     NaN   NaN   NaN    NaN         NaN   NaN
49  67.0   97.0    NaN  157.0  106.33   NaN  16.0    NaN         NaN   NaN
50  62.0   97.0    NaN  128.0   90.00  70.0  16.0    NaN         NaN  24.0
51  71.0   97.0  37.72  149.0  102.00  82.0  16.0    NaN         NaN   NaN
52  76.0   97.0    NaN  136.0  102.00  83.0  16.0    NaN         0.0   NaN
53  74.0   98.0    NaN  137.0  100.00  80.0  16.0    NaN         NaN   NaN
54  78.0   97.0    NaN  137.0  101.00  81.0  16.0    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  47.42       0      1      0        -0.02       4
1   ...        NaN  47.42       0      1      0        -0.02       5
2   ...        NaN  47.42       0      1      0        -0.02       6
3   ...        NaN  47.42       0      1      0        -0.02       7
4   ...        NaN  47.42       0      1      0        -0.02       8
5   ...        NaN  47.42       0      1      0        -0.02       9
6   ...        NaN  47.42       0      1      0        -0.02      10
7   ...        NaN  47.42       0      1      0        -0.02      11
8   ...        NaN  47.42       0      1      0        -0.02      12
9   ...      178.0  47.42       0      1      0        -0.02      13
10  ...        NaN  47.42       0      1      0        -0.02      14
11  ...        NaN  47.42       0      1      0        -0.02      15
12  ...        NaN  47.42       0      1      0        -0.02      16
13  ...        NaN  47.42       0      1      0        -0.02      17
14  ...        NaN  47.42       0      1      0        -0.02      18
15  ...        NaN  47.42       0      1      0        -0.02      19
16  ...        NaN  47.42       0      1      0        -0.02      20
17  ...        NaN  47.42       0      1      0        -0.02      21
18  ...        NaN  47.42       0      1      0        -0.02      22
19  ...        NaN  47.42       0      1      0        -0.02      23
20  ...        NaN  47.42       0      1      0        -0.02      24
21  ...        NaN  47.42       0      1      0        -0.02      25
22  ...        NaN  47.42       0      1      0        -0.02      26
23  ...        NaN  47.42       0      1      0        -0.02      27
24  ...        NaN  47.42       0      1      0        -0.02      28
25  ...        NaN  47.42       0      1      0        -0.02      29
26  ...        NaN  47.42       0      1      0        -0.02      30
27  ...        NaN  47.42       0      1      0        -0.02      31
28  ...        NaN  47.42       0      1      0        -0.02      32
29  ...        NaN  47.42       0      1      0        -0.02      33
30  ...        NaN  47.42       0      1      0        -0.02      34
31  ...        NaN  47.42       0      1      0        -0.02      35
32  ...        NaN  47.42       0      1      0        -0.02      36
33  ...        NaN  47.42       0      1      0        -0.02      37
34  ...      163.0  47.42       0      1      0        -0.02      38
35  ...        NaN  47.42       0      1      0        -0.02      39
36  ...        NaN  47.42       0      1      0        -0.02      40
37  ...        NaN  47.42       0      1      0        -0.02      41
38  ...        NaN  47.42       0      1      0        -0.02      42
39  ...        NaN  47.42       0      1      0        -0.02      43
40  ...        NaN  47.42       0      1      0        -0.02      44
41  ...        NaN  47.42       0      1      0        -0.02      45
42  ...        NaN  47.42       0      1      0        -0.02      46
43  ...        NaN  47.42       0      1      0        -0.02      47
44  ...        NaN  47.42       0      1      0        -0.02      48
45  ...        NaN  47.42       0      1      0        -0.02      49
46  ...        NaN  47.42       0      1      0        -0.02      50
47  ...        NaN  47.42       0      1      0        -0.02      51
48  ...        NaN  47.42       0      1      0        -0.02      52
49  ...        NaN  47.42       0      1      0        -0.02      53
50  ...        NaN  47.42       0      1      0        -0.02      54
51  ...        NaN  47.42       0      1      0        -0.02      55
52  ...        NaN  47.42       0      1      0        -0.02      56
53  ...        NaN  47.42       0      1      0        -0.02      57
54  ...        NaN  47.42       0      1      0        -0.02      58

    SepsisLabel  qSOFA  SOFA
0             0      1     0
1             0      1     0
2             0      1     0
3             0      1     0
4             0      1     0
5             0      1     0
6             0      1     0
7             0      0     0
8             0      0     0
9             0      1     0
10            0      1     0
11            0      0     0
12            0      1     0
13            0      0     0
14            0      1     0
15            0      0     0
16            0      0     0
17            0      0     0
18            0      1     0
19            0      0     0
20            0      1     0
21            0      1     0
22            0      1     0
23            0      0     0
24            0      0     0
25            0      0     0
26            0      0     0
27            0      0     0
28            0      0     0
29            0      1     0
30            0      0     0
31            0      0     0
32            0      0     0
33            0      0     0
34            0      0     0
35            0      0     0
36            0      0     0
37            0      0     0
38            0      0     0
39            0      1     0
40            0      0     0
41            0      1     0
42            0      0     0
43            0      0     0
44            0      0     0
45            1      0     0
46            1      0     0
47            1      0     0
48            1      0     0
49            1      0     0
50            1      0     0
51            1      0     0
52            1      0     0
53            1      0     0
54            1      0     0

[55 rows x 43 columns]
      HR  O2Sat   Temp    SBP   MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  ...  \
0   68.0   97.0    NaN  138.0  88.0  NaN  18.0    NaN         NaN   NaN  ...
1   67.0   96.0  36.78  132.0  86.0  NaN  15.0    NaN         NaN   NaN  ...
2   66.0   96.5    NaN  136.0  84.5  NaN  16.5    NaN         NaN  27.0  ...
3   63.0   95.0    NaN  127.0  84.0  NaN  14.0    NaN         NaN  27.0  ...
4   62.0   96.0    NaN  126.0  81.0  NaN  14.0    NaN         NaN   NaN  ...
5   62.0   95.0  36.78  128.0  79.0  NaN  14.0    NaN         NaN   NaN  ...
6   56.0   92.0    NaN  109.0  74.0  NaN  15.0    NaN         NaN   NaN  ...
7   57.0   92.0    NaN  131.0  69.0  NaN  18.0    NaN         NaN   NaN  ...
8   56.0   93.0    NaN  107.0  70.0  NaN  14.0    NaN         NaN   NaN  ...
9   55.0   93.0    NaN  117.0  51.0  NaN  16.0    NaN         NaN   NaN  ...
10  61.0   96.0  36.67  109.0  68.0  NaN  13.0    NaN         NaN   NaN  ...
11  54.0   95.0    NaN  103.0  63.0  NaN  11.0    NaN         NaN  30.0  ...
12   NaN    NaN    NaN    NaN   NaN  NaN   NaN    NaN         NaN  30.0  ...
13  65.0   97.0  36.89  124.0  78.0  NaN  12.0    NaN         NaN   NaN  ...
14  61.0    NaN    NaN  112.0  73.0  NaN  18.0    NaN         NaN   NaN  ...
15  60.0    NaN    NaN  132.0  71.0  NaN  18.0    NaN         NaN   NaN  ...
16  69.0    NaN    NaN  119.0  75.0  NaN  24.0    NaN         NaN   NaN  ...
17  62.0    NaN    NaN  136.0  82.0  NaN  18.0    NaN         NaN   NaN  ...
18  63.0    NaN    NaN  131.0  77.0  NaN  14.0    NaN         NaN   NaN  ...


       HR  O2Sat   Temp    SBP    MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  \
0   110.0   98.0  37.67  124.0  78.00  NaN  16.0    NaN         NaN   NaN
1   103.0   96.0    NaN  101.0  69.67  NaN   NaN    NaN         NaN   NaN
2   105.0   96.0    NaN  125.0  75.67  NaN   NaN    NaN         NaN   NaN
3   118.0   94.0    NaN  150.0  94.67  NaN   NaN    NaN         NaN   NaN
4    99.0   94.0  37.50   98.0  64.00  NaN   NaN    NaN         NaN   NaN
5   104.0   93.0    NaN  104.0  67.33  NaN   NaN    NaN         NaN   NaN
6     NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
7     NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
8    97.0   93.0    NaN   95.0  59.67  NaN  16.0    NaN         NaN   NaN
9     NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
10  108.0   94.0    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
11    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
12  103.0   92.0    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
13    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
14  100.0   95.0  37.28  121.0  20.00  NaN   NaN    NaN         NaN  22.0
15    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
16  106.0   94.0  37.11  134.0  81.33  NaN   NaN    NaN         NaN   NaN
17    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN
18   97.0   95.0    NaN  125.0  80.33  NaN  18.0    NaN         NaN   NaN
19   86.0   95.0  36.89    NaN    NaN  NaN   NaN    NaN         NaN   NaN
20   85.0   95.0  37.67  120.0  74.00  NaN   NaN    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  81.64       1      1      0        -0.03       2
1   ...        NaN  81.64       1      1      0        -0.03       3
2   ...        NaN  81.64       1      1      0        -0.03       4
3   ...        NaN  81.64       1      1      0        -0.03       5
4   ...        NaN  81.64       1      1      0        -0.03       6
5   ...        NaN  81.64       1      1      0        -0.03       7
6   ...        NaN  81.64       1      1      0        -0.03       8
7   ...        NaN  81.64       1      1      0        -0.03       9
8   ...        NaN  81.64       1      1      0        -0.03      10
9   ...        NaN  81.64       1      1      0        -0.03      11
10  ...        NaN  81.64       1      1      0        -0.03      12
11  ...        NaN  81.64       1      1      0        -0.03      13
12  ...        NaN  81.64       1      1      0        -0.03      14
13  ...        NaN  81.64       1      1      0        -0.03      15
14  ...      127.0  81.64       1      1      0        -0.03      16
15  ...        NaN  81.64       1      1      0        -0.03      17
16  ...        NaN  81.64       1      1      0        -0.03      18
17  ...        NaN  81.64       1      1      0        -0.03      19
18  ...        NaN  81.64       1      1      0        -0.03      20
19  ...        NaN  81.64       1      1      0        -0.03      21
20  ...        NaN  81.64       1      1      0        -0.03      22

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      0     0
2             0      0     0
3             0      0     0
4             0      1     0
5             0      0     0
6             0      0     0
7             0      0     0
8             0      1     0
9             0      0     0
10            0      0     0
11            0      0     0
12            0      0     0
13            0      0     0
14            0      0     0
15            0      0     0
16            0      0     0
17            0      0     0
18            0      0     0
19            0      0     0
20            0      0     0

[21 rows x 43 columns]
       HR  O2Sat   Temp     SBP   MAP    DBP   Resp  EtCO2  BaseExcess  HCO3  \
0    80.0  100.0    NaN  120.50  70.5  54.00  16.00    NaN         0.0  22.0
1    88.0  100.0  36.90   95.50  62.0  51.00  16.00    NaN         NaN   NaN
2    83.0  100.0  37.00  100.25  63.5  52.00  16.00    NaN        -4.0   NaN
3    74.5  100.0  37.50   90.25  60.0  50.50  16.00    NaN        -3.0   NaN
4    88.0  100.0  37.40   77.50  57.0  50.00  14.00    NaN         NaN  20.0
5    88.0  100.0  37.40   85.75  62.0  51.75  14.00    NaN         NaN   NaN
6    88.0  100.0  37.60  100.75  69.0  55.50  18.00    NaN         NaN   NaN
7    88.0  100.0  37.60  111.00  72.0  55.50  19.00    NaN         NaN   NaN
8    89.0   98.0  37.80   82.00  58.0  48.00  20.50    NaN        -3.0   NaN
9    92.0   97.0  37.80   95.33  49.0  56.50  20.00    NaN         NaN   NaN
10   91.5   96.0  38.00  105.50  68.5  53.75  23.00    NaN         NaN   NaN
11   88.0   96.0  37.90  104.00  68.0  54.00  17.00    NaN        -3.0   NaN
12   78.0   97.0  38.10   86.50  61.0  53.50  16.00    NaN         NaN   NaN
13   84.0   97.0  38.20   80.00  59.0  52.00  22.50    NaN         NaN   NaN
14   82.0   95.0  38.20   97.00  62.0  47.50  16.00    NaN         NaN   NaN
15   75.0   97.0  38.10  109.00  65.0  49.00  14.00    NaN        -3.0   NaN
16   75.0   97.0  38.20  109.00  65.0  50.00   9.00    NaN         NaN   NaN
17   74.0   97.0  38.10  111.00  66.0  50.00  14.50    NaN         NaN   NaN
18   80.0   96.0  38.20  112.00  66.0  48.00  17.00    NaN         NaN   NaN
19   84.0   96.0  38.10  119.00  69.0  49.00  14.00    NaN         NaN   NaN
20   85.0   96.0  38.10  117.00  69.0  49.00  15.00    NaN        -2.0   NaN
21   87.0   97.0  38.20  125.00  72.0  52.00  16.00    NaN         NaN   NaN
22   85.0   95.0  38.10  115.50  64.0  49.00  16.00    NaN         NaN   NaN
23   84.0   95.0  37.90  105.00  62.0  46.00  15.00    NaN         NaN   NaN
24   86.0   95.0  37.90  102.00  61.0  45.00  14.00    NaN         NaN   NaN
25   86.0   96.0  37.90  109.00  68.0  52.00  20.00    NaN         NaN   NaN
26   89.5   96.5  38.00  116.50  71.0  54.00  19.00    NaN         NaN   NaN
27   84.0   96.0  37.90  110.00  66.0  49.00  15.00    NaN         NaN   NaN
28   86.0   96.0  38.00  111.00  66.0  49.00  17.00    NaN         1.0  27.0
29   88.0   95.5  38.00  114.50  68.0  50.50  17.75    NaN         NaN   NaN
30   90.0   95.0  38.00  114.00  68.0  51.00  17.00    NaN         NaN   NaN
31  100.5   95.0  38.00  123.50  78.5  61.00  19.50    NaN         1.0   NaN
32  100.0   95.0  37.80  111.00  71.0  55.00  18.00    NaN         2.0   NaN
33   90.0   95.0  37.80  119.00  73.0  55.00  16.00    NaN         NaN   NaN
34   93.0   96.0  37.30   99.00  63.0  49.00  14.00    NaN         NaN   NaN
35   83.0   97.0    NaN   99.00  62.0    NaN  16.00    NaN         0.0   NaN
36  100.0   99.0    NaN  106.00  72.0    NaN  15.00    NaN         NaN   NaN
37   88.0   99.0  36.72  114.00  67.0    NaN  18.00    NaN         NaN   NaN
38  100.0   98.0    NaN  116.00  69.0    NaN  16.00    NaN         NaN   NaN
39  103.0   98.0    NaN  117.00  64.0    NaN  20.00    NaN         NaN   NaN
40  103.0   98.0    NaN  108.00  60.0    NaN  20.00    NaN         NaN   NaN
41  108.0   99.0    NaN  108.00  64.0    NaN  24.00    NaN         NaN   NaN

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...      117.0  73.43       1      0      1        -7.05       2
1   ...        NaN  73.43       1      0      1        -7.05       3
2   ...        NaN  73.43       1      0      1        -7.05       4
3   ...        NaN  73.43       1      0      1        -7.05       5
4   ...      172.0  73.43       1      0      1        -7.05       6
5   ...        NaN  73.43       1      0      1        -7.05       7
6   ...        NaN  73.43       1      0      1        -7.05       8
7   ...        NaN  73.43       1      0      1        -7.05       9
8   ...        NaN  73.43       1      0      1        -7.05      10
9   ...        NaN  73.43       1      0      1        -7.05      11
10  ...        NaN  73.43       1      0      1        -7.05      12
11  ...        NaN  73.43       1      0      1        -7.05      13
12  ...        NaN  73.43       1      0      1        -7.05      14
13  ...        NaN  73.43       1      0      1        -7.05      15
14  ...        NaN  73.43       1      0      1        -7.05      16
15  ...        NaN  73.43       1      0      1        -7.05      17
16  ...        NaN  73.43       1      0      1        -7.05      18
17  ...        NaN  73.43       1      0      1        -7.05      19
18  ...        NaN  73.43       1      0      1        -7.05      20
19  ...        NaN  73.43       1      0      1        -7.05      21
20  ...        NaN  73.43       1      0      1        -7.05      22
21  ...        NaN  73.43       1      0      1        -7.05      23
22  ...        NaN  73.43       1      0      1        -7.05      24
23  ...        NaN  73.43       1      0      1        -7.05      25
24  ...        NaN  73.43       1      0      1        -7.05      26
25  ...        NaN  73.43       1      0      1        -7.05      27
26  ...        NaN  73.43       1      0      1        -7.05      28
27  ...        NaN  73.43       1      0      1        -7.05      29
28  ...      140.0  73.43       1      0      1        -7.05      30
29  ...        NaN  73.43       1      0      1        -7.05      31
30  ...        NaN  73.43       1      0      1        -7.05      32
31  ...        NaN  73.43       1      0      1        -7.05      33
32  ...        NaN  73.43       1      0      1        -7.05      34
33  ...        NaN  73.43       1      0      1        -7.05      35
34  ...        NaN  73.43       1      0      1        -7.05      36
35  ...        NaN  73.43       1      0      1        -7.05      37
36  ...        NaN  73.43       1      0      1        -7.05      38
37  ...        NaN  73.43       1      0      1        -7.05      39
38  ...        NaN  73.43       1      0      1        -7.05      40
39  ...        NaN  73.43       1      0      1        -7.05      41
40  ...        NaN  73.43       1      0      1        -7.05      42
41  ...        NaN  73.43       1      0      1        -7.05      43

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      1     0
2             0      0     0
3             0      1     0
4             0      1     0
5             0      1     0
6             0      0     0
7             0      0     0
8             0      1     0
9             0      1     0
10            0      1     0
11            0      0     0
12            0      1     0
13            0      1     0
14            0      1     0
15            0      0     0
16            0      0     0
17            0      0     0
18            0      0     0
19            0      0     0
20            0      0     0
21            0      0     0
22            0      0     0
23            0      0     0
24            0      0     0
25            0      0     0
26            0      0     0
27            0      0     0
28            0      0     0
29            0      0     0
30            0      0     0
31            0      0     0
32            0      0     0
33            0      0     0
34            0      1     0
35            0      1     0
36            0      0     0
37            0      0     0
38            0      0     0
39            0      0     0
40            0      0     0
41            0      1     0

[42 rows x 43 columns]
      HR  O2Sat   Temp     SBP   MAP   DBP  Resp  EtCO2  BaseExcess  HCO3  \
0    NaN    NaN    NaN     NaN   NaN   NaN   NaN    NaN         NaN   NaN
1   73.0   99.0  36.06  100.00  67.0  49.5  16.5    NaN        -8.0  16.0
2   73.0  100.0    NaN  108.00  74.0  56.0  16.0    NaN       -10.0  16.0
3   80.0   95.0  36.33   89.00  62.0  47.0  22.0    NaN       -10.0   NaN
4   77.0  100.0    NaN  105.00  70.0  51.0  20.0    NaN         NaN   NaN
5   75.0  100.0    NaN  108.50  65.0  52.0  19.0    NaN         NaN  15.0
6   75.0  100.0    NaN  108.00  69.0  51.0  13.0    NaN        -7.0  15.0
7   79.0  100.0  36.67  103.50  63.0  52.0  16.0    NaN        -7.0   NaN
8   80.0  100.0    NaN  103.75  58.0  55.0  18.0    NaN         NaN   NaN
9   79.0  100.0    NaN   96.50  61.0  47.0  17.0    NaN         NaN   NaN
10  78.0  100.0    NaN  105.00  70.0  50.0  20.0    NaN         NaN   NaN
11  80.0  100.0  36.89  103.00  61.0  49.0  18.0    NaN        -6.0  16.0
12  86.0  100.0    NaN   97.50  65.0  49.0  19.0    NaN        -6.0  16.0
13  82.0   98.0    NaN  113.00  65.0  42.0  15.0    NaN         NaN   NaN
14  87.0  100.0    NaN   98.00  61.0  42.0  16.0    NaN         NaN   NaN
15  88.0   99.0    NaN   97.00  63.0  44.0  16.0    NaN         NaN   NaN
16  88.0  100.0  36.67  117.00  71.0  50.0  18.0    NaN         NaN  15.0
17  86.0  100.0    NaN  113.00  73.0  51.0  16.0    NaN         NaN  15.0
18  85.0  100.0  36.56  111.00  69.0  48.0  18.0    NaN         NaN   NaN
19  72.0  100.0    NaN   99.00  58.0  40.0  15.0    NaN         NaN   NaN
20  72.0  100.0    NaN   99.00  57.0  40.0  12.0    NaN         NaN   NaN
21  74.0  100.0    NaN  114.00  63.0  44.0  12.0    NaN         NaN   NaN
22  75.0   79.0  36.22  120.00  68.0  46.0  17.0    NaN         NaN  15.0
23  72.0  100.0    NaN  115.00  62.0  49.0  18.0    NaN         NaN  15.0
24  72.0   98.0    NaN  114.00  64.0  45.0  15.0    NaN         NaN   NaN
25  71.0   99.0    NaN  115.00  67.0  48.0  16.0    NaN         NaN   NaN
26  71.0  100.0    NaN  109.00  61.0  43.0  13.0    NaN         NaN   NaN
27  81.0   97.0  35.67  116.00  72.0  51.0  18.0    NaN         NaN   NaN
28  77.0   89.0    NaN  122.00  75.0  52.0  17.0    NaN         NaN   NaN
29  72.0   97.0    NaN  114.00  63.0  44.0  16.0    NaN       -10.0   NaN
30  71.0    NaN    NaN  109.00  66.0  46.0  16.0    NaN       -10.0   NaN
31  65.0   98.0  36.00  103.00  58.0  41.0  13.0    NaN         NaN   NaN
32  65.0   96.0    NaN  108.00  60.0  42.0  15.0    NaN         NaN   NaN
33  68.0  100.0    NaN  108.00  62.0  44.0  17.0    NaN        -8.0   NaN
34   NaN    NaN    NaN     NaN   NaN   NaN   NaN    NaN        -8.0   NaN
35  71.0   96.0  36.00  127.00  70.0  48.0  18.0    NaN         NaN   NaN
36  73.0    NaN    NaN  115.00  70.0  49.0  17.0    NaN       -11.0   NaN
37  72.0   89.0    NaN  119.00  70.0  49.0  19.0    NaN       -11.0   NaN
38  72.0   97.0  36.17  135.00  74.0  50.0  18.0    NaN         NaN   NaN
39  84.0   95.0    NaN  136.00  81.0  53.0  15.0    NaN        -6.0  17.0

    ...  Platelets    Age  Gender  Unit1  Unit2  HospAdmTime  ICULOS  \
0   ...        NaN  87.08       1    NaN    NaN        -2.23       1
1   ...      357.0  87.08       1    NaN    NaN        -2.23       2
2   ...        NaN  87.08       1    NaN    NaN        -2.23       3
3   ...        NaN  87.08       1    NaN    NaN        -2.23       4
4   ...        NaN  87.08       1    NaN    NaN        -2.23       5
5   ...        NaN  87.08       1    NaN    NaN        -2.23       6
6   ...        NaN  87.08       1    NaN    NaN        -2.23       7
7   ...        NaN  87.08       1    NaN    NaN        -2.23       8
8   ...        NaN  87.08       1    NaN    NaN        -2.23       9
9   ...        NaN  87.08       1    NaN    NaN        -2.23      10
10  ...        NaN  87.08       1    NaN    NaN        -2.23      11
11  ...        NaN  87.08       1    NaN    NaN        -2.23      12
12  ...        NaN  87.08       1    NaN    NaN        -2.23      13
13  ...        NaN  87.08       1    NaN    NaN        -2.23      14
14  ...        NaN  87.08       1    NaN    NaN        -2.23      15
15  ...        NaN  87.08       1    NaN    NaN        -2.23      16
16  ...      213.0  87.08       1    NaN    NaN        -2.23      17
17  ...        NaN  87.08       1    NaN    NaN        -2.23      18
18  ...        NaN  87.08       1    NaN    NaN        -2.23      19
19  ...        NaN  87.08       1    NaN    NaN        -2.23      20
20  ...        NaN  87.08       1    NaN    NaN        -2.23      21
21  ...        NaN  87.08       1    NaN    NaN        -2.23      22
22  ...      205.0  87.08       1    NaN    NaN        -2.23      23
23  ...        NaN  87.08       1    NaN    NaN        -2.23      24
24  ...        NaN  87.08       1    NaN    NaN        -2.23      25
25  ...        NaN  87.08       1    NaN    NaN        -2.23      26
26  ...        NaN  87.08       1    NaN    NaN        -2.23      27
27  ...        NaN  87.08       1    NaN    NaN        -2.23      28
28  ...        NaN  87.08       1    NaN    NaN        -2.23      29
29  ...        NaN  87.08       1    NaN    NaN        -2.23      30
30  ...        NaN  87.08       1    NaN    NaN        -2.23      31
31  ...        NaN  87.08       1    NaN    NaN        -2.23      32
32  ...        NaN  87.08       1    NaN    NaN        -2.23      33
33  ...        NaN  87.08       1    NaN    NaN        -2.23      34
34  ...        NaN  87.08       1    NaN    NaN        -2.23      35
35  ...        NaN  87.08       1    NaN    NaN        -2.23      36
36  ...        NaN  87.08       1    NaN    NaN        -2.23      37
37  ...        NaN  87.08       1    NaN    NaN        -2.23      38
38  ...        NaN  87.08       1    NaN    NaN        -2.23      39
39  ...        NaN  87.08       1    NaN    NaN        -2.23      40

    SepsisLabel  qSOFA  SOFA
0             0      0     0
1             0      1     0
2             0      0     0
3             0      1     0
4             0      0     0
5             0      0     0
6             0      0     0
7             0      0     0
8             0      0     0
9             0      1     0
10            0      0     0
11            0      0     0
12            0      1     0
13            0      0     0
14            0      1     0
15            0      1     0
16            0      0     0
17            0      0     0
18            0      0     0
19            0      1     0
20            0      1     0
21            0      0     0
22            0      0     0
23            0      0     0
24            0      0     0
25            0      0     0
26            0      0     0
27            0      0     0
28            0      0     0
29            0      0     0
30            0      0     0
31            0      0     0
32            0      0     0
33            0      0     0
34            0      0     0
35            0      0     0
36            0      0     0
37            0      0     0
38            0      0     0
39            0      0     0

[40 rows x 43 columns]
      HR  O2Sat   Temp    SBP    MAP  DBP  Resp  EtCO2  BaseExcess  HCO3  ...  \
0    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN  ...
1    NaN    NaN    NaN    NaN    NaN  NaN   NaN    NaN         NaN   NaN  ...
2   74.0  100.0  37.11  109.0  84.33  NaN  15.0    NaN         NaN   NaN  ...
3   69.0   99.0    NaN  104.0  79.67  NaN  16.0    NaN         NaN   NaN  ...
4   68.0  100.0    NaN  110.0  81.33  NaN  14.0    NaN         NaN   NaN  ...
5   67.0  100.0    NaN  107.0  81.00  NaN  15.0    NaN         NaN   NaN  ...
6   69.5  100.0  37.17  109.5  71.00  NaN  17.5    NaN         NaN  24.0  ...
7   64.0  100.0    NaN   94.0  66.00  NaN  18.0    NaN         NaN   NaN  ...
8   70.0  100.0    NaN  111.0  79.67  NaN  21.0    NaN         NaN   NaN  ...
9   76.0  100.0    NaN  105.0  82.33  NaN  16.0    NaN         NaN   NaN  ...
10  73.0   99.5    NaN  108.0  81.67  NaN  17.5    NaN         NaN   NaN  ...
11  71.0  100.0    NaN  120.0  87.33  NaN  15.0    NaN         NaN   NaN  ...
12  66.0  100.0  36.78  107.0  77.00  NaN  18.0    NaN         NaN   NaN  ...
13  74.0    NaN    NaN  111.0  75.00  NaN  17.0    NaN         NaN   NaN  ...
14  70.0   97.0  36.56   88.0  60.67  NaN  18.0    NaN         NaN   NaN  ...
15  64.0   97.0    NaN   89.0  65.67  NaN  16.0    NaN         NaN   NaN  ...
16  65.0    NaN  36.17   96.0  68.00  NaN  18.0    NaN         NaN   NaN  ...
17  68.5   98.0    NaN   93.5  66.17  NaN  14.5    NaN         NaN   NaN  ...